### PR TITLE
Check for colliding component FVKs

### LINKED ISSUE #1474: Precisely document same-UFVK errors on account creation and ensure they are per-component
This is an issue with #1465 found in post-hoc review.

_Originally posted by @daira in https://github.com/zcash/librustzcash/pull/1465#discussion_r1695972600_

> Should this say "If an account created via [`WalletWrite::create_account`] or imported via [`WalletWrite::import_account_ufvk`] or [`WalletWrite::import_account_hd`] already exists in the wallet with the same UFVK (which will also be the case for accounts with the same seed), an error will be returned." ?
>
> This differs from the current wording because (I think) it is not the case that the creation or import has to be in any particular order; any of these three methods will fail if it produces a duplicate UFVK, regardless of which of them was used to create the existing account. At least, if that's not the case then it is a bug.
>
> Also, do we actually mean "same UFVK" here, or do we mean that there will be a failure if *any component* of the UFVK matches that of an existing account? In the case of an account where we don't know the seed, the imported UFVK can't include components that are not known yet, and *may not* include some existing components (I don't know whether the latter is supported).

_Originally posted by @daira in https://github.com/zcash/librustzcash/pull/1465#discussion_r1695982562_

> I think the doc for each of the three account creation/import methods should call out that it fails when there is a duplicate UFVK, even if that's redundant with the `WalletWrite` doc. Note that it is possible to hit this case even if you only use one of the three methods, and there might be implementors who only read the documentation of the methods they are using (because they haven't reached [this page](https://hmpg.net/) yet).

### PR DESCRIPTION
**Pull request by daira**
When adding an account, check whether any component of its UFVK (if available) collides with an existing imported or derived FVK.

This does not check for collisions on IVK for `Incoming` accounts (#1490), which is okay because those are not yet exposed in the public API.

Builds on #1479, fixes #1474

### CODE REVIEW

File: zcash_client_sqlite/src/wallet.rs [hunk 1]
```diff
@@ -427,8 +435,9 @@ pub(crate) fn add_account<P: consensus::Parameters>(
             rusqlite::Error::SqliteFailure(f, s)
                 if f.code == rusqlite::ErrorCode::ConstraintViolation =>
             {
-                // An account conflict occurred.
-                // Make a best effort to determine the AccountId of the pre-existing row
+                // An account conflict occurred. This should already have been caught by
+                // the check using `get_account_for_ufvk` above, but in case it wasn't,
+                // make a best effort to determine the AccountId of the pre-existing row
                 // and provide that to our caller.
```
Comment (daira) [inline zcash_client_sqlite/src/wallet.rs:441]: This code will no longer be reached when a collision occurs, which explains the small reduction in test coverage.

File: zcash_client_sqlite/src/lib.rs [hunk 2]
```diff
@@ -2198,13 +2260,16 @@ mod tests {
...
 
         let seed = Secret::new(vec![0u8; 32]);
+        let zip32_index_0 = zip32::AccountId::ZERO;
         let seed_based = st.wallet_mut().create_account(&seed, &birthday).unwrap();
         let seed_based_account = st.wallet().get_account(seed_based.0).unwrap().unwrap();
         let ufvk = seed_based_account.ufvk().unwrap();
 
         assert_matches!(
-            st.wallet_mut().import_account_ufvk(ufvk, &birthday, AccountPurpose::Spending),
+            st.wallet_mut().import_account_hd(&seed, zip32_index_0, &birthday),
```
Comment (daira) [inline zcash_client_sqlite/src/lib.rs:2269]: The `import_account_ufvk` check is done in `check_collisions` below, so this is adding an extra check for collisions between `create_account` and `import_account_hd`.

**Review by nuttycom — APPROVED** [review]
utACK bd38645da54cfaa24935cd0001bef5a1a0054eb2

**Comment by str4d** [comment]
Post-hoc utACK bd38645da54cfaa24935cd0001bef5a1a0054eb2
