### PR TITLE
zcash_client_sqlite: Ensure that all shielded change outputs are correctly flagged.

### LINKED ISSUE #1571: Bug in is_shielding state going from TRUE to FALSE after the first confirmation
- the states of the DB and is_shielding changes from true to false

How to reproduce:
- I tapped a button to shield my funds, it:
- created a transaction in a pending state with is_shielding TRUE
- after 1st confirmation, it flipped to sending instead of shielding, I checked the DB and there is no TRUE anymore (see the DB)
- after 10 confirmations, it flipped to sent
- when I restore the same wallet, I see shielded again

Few more observations:
- when I try to restore the wallet on a different simulator while it’s still waiting on 10 confirmations and should be shielding funds but it’s sending, I see correct state restored.. so restore is able to bring the TRUE flag back but where it matters it’s broken

- db export shared via Slack here: https://zcash.slack.com/archives/C02C1GZ0R6F/p1724835111523729

### PR DESCRIPTION
**Pull request by nuttycom**
Fixes #1571

### CODE REVIEW

File: zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs [hunk 1]
```diff
@@ -0,0 +1,198 @@
...
+        assert_eq!(tx.spent_note_count(), 1);
+        assert!(tx.has_change());
+        assert_eq!(tx.received_note_count(), 0);
+        assert_eq!(tx.sent_note_count(), 0);
+        assert!(tx.is_shielding());
+
+        // Complete the migration
+        init_wallet_db(st.wallet_mut().db_mut(), None).unwrap();
+
+        // Ensure that the transaction metadata is still correct after the update produced by scanning.
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs:176]: What scanning update? AFAICT this test doesn't do one; it just checks that the unscanned shielding transaction's metadata is not altered by the migration. It might indeed be useful to have two tests for this migration: one that ensures correct data isn't altered, and one that ensures incorrect data gets fixed.

File: zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs [hunk 2]
```diff
@@ -0,0 +1,198 @@
...
+
+    fn up(&self, transaction: &rusqlite::Transaction) -> Result<(), WalletMigrationError> {
+        let fix_change_flag = |table_prefix| {
+            transaction.execute(
+                &format!(
+                    "UPDATE {table_prefix}_received_notes
+                     SET is_change = 1
+                     FROM sent_notes sn
+                     WHERE sn.tx = {table_prefix}_received_notes.tx
+                     AND sn.from_account_id = {table_prefix}_received_notes.account_id
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs:52]: This won't catch cross-account wallet-internal transfers, but I think that's okay.

File: zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs [hunk 3]
```diff
@@ -0,0 +1,198 @@
...
+                     AND {table_prefix}_received_notes.recipient_key_scope = :internal_scope"
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs:53]: This restriction means that funds sent from an account to itself via its external address will not be updated here. For modern wallets that makes sense, but for historic wallets (when internal scope didn't exist) a "change" output was simply an output received by the account in a tx that the account also spent funds in. Do we have reason to believe that those earlier transactions are or are not affected by this bug?

File: zcash_client_sqlite/src/wallet.rs [hunk 4]
```diff
@@ -3221,9 +3221,38 @@ fn recipient_params<P: consensus::Parameters>(
...
+    conn: &rusqlite::Transaction,
+    tx_ref: TxRef,
+) -> Result<(), SqliteClientError> {
+    let flag_received_change = |table_prefix| {
+        conn.execute(
+            &format!(
+                "UPDATE {table_prefix}_received_notes 
+                 SET is_change = 1
+                 FROM sent_notes sn
+                 WHERE sn.tx = {table_prefix}_received_notes.tx
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet.rs:3234]: What kind of join does this implicitly do? (both here and in the migration which has an identical query)

It might be useful to add a comment describing the intent of this query.

**Review by str4d — COMMENTED** [review]
Reviewed 0d82e1efc50aff89db715df1065f6a331701b361

File: zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs (hunk 2 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs:52]: That's actually intentional; a cross-account wallet-internal transfer output isn't change.

File: zcash_client_sqlite/src/wallet.rs (hunk 4 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/wallet.rs:3234]: This is implicitly an inner join, the same as you get whenever you use a `FROM` clause with multiple tables and then use `WHERE` to perform the joins.

File: zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs (hunk 3 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs:53]: The legacy shielding transactions likely _will_ be affected by this problem in wallet recovery. However, I think that's acceptable; the wallets at the time those transactions were created did not show "shielding" for those transactions in wallet history, so this leaves that part of the transaction history essentially unmodified from the user's perspective.

File: zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs (hunk 1 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs:176]: Copy/paste error - this comment was correct in the test for the change from `IS_NULL` to `MAX`, and the test is the same.

Comment (nuttycom) [reply zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs]: [force-pushed](https://github.com/zcash/librustzcash/compare/0d82e1e..d75309080106639920f8302e555f482dfc35e6c2) to address comment.

**Comment by nuttycom** [comment]
[force-pushed](https://github.com/zcash/librustzcash/compare/bca02d5c148d8e080f52ce32e1936fb55c8df62f..d75309080106639920f8302e555f482dfc35e6c2) to rebase on `main`.

**Review by str4d — APPROVED** [review]
utACK d75309080106639920f8302e555f482dfc35e6c2

**Review by daira — COMMENTED** [review]
Post-hoc ACK
