### PR TITLE
zcash_client_sqlite: Use consistent criteria for detecting what accounts fund a transaction.

### LINKED ISSUE #1304: v_tx_outputs `from_account_id` column left NULL for notes sent to self
This issue screws up running balance calculations in my app, by interfering with the ability to detect 'change' line items in a transaction.  I expect change rows in `v_tx_outputs` to have `from_account_id` and `to_account_id` set to the same value, but instead, `from_account_id` is set to NULL, suggesting that all change is novel _income_ for the account, causing running balance to skyrocket.

I believe this is a recent regression in librustzcash because I had running balance working until I merged recently to get the orchard changes.

Repro steps:

Execute account recovery using this UFVK:
```
uviewtest1tcygrtut692vqlx9nlyknx0fqq59am5vhaf97gxncqnfn87qrgey68777tumstc2lcp4r9yxd3fknkpmxtgw8awhcg40cw00ahvtaeqmpfqvjz6e3v234zsfvdvt6dm8dpzxv970wkdv2jrfm3t2m9cde9ry8mrxr286ns4yqwmcx3k4netqqhgldthnhzhlpg0lk00eruy4tf3fx3k9xn7fywppj8wyzjjc3dcrqe6kxnc6zxpfly9e2uk3k7jyy3n70zpj5zfheedzz0sw2pp96rvy9xt2dw94nplfx0usrwtshrmf5xwq84qcq459kvks5g28gvkxrjpujgc9gkjt5np5m4afruk0z8zlyd65hfqqu9pg3u9lkk26r7ad4l59yy3tn2xlmad42a6kee8l92ddj7tgf4fhv4x9thx7kf28jc6gvf3xr3lhtegd8ly590595g6dfh3w7nalmt8zx6yestgfqu9uvg8gkwkwmuc4u5jsecqu
```
(or, if you prefer, use the same seed phrase that I privately sent to @nuttycom over Signal).

Open the sqlite data file in DB Browser for SQLite and inspect the `v_tx_outputs` table:

image

The selection in the above screenshot show the two outputs of a particular orchard transaction. The top one is change, but notice how `from_account_id` is `NULL`.
It's the same for _all_ change in this table. In fact you can see not a single row has both `from_account_id` and `to_account_id` set to non-NULL values, which is of course highly suspicious, as that would require every one of 21 transactions to have exactly no change.

In fact it isn't just change. One transaction in this account's history records an explicit 'send to self' transaction. Both the user amount and the change amount rows have `from_account_id` left at NULL.
image

### PR DESCRIPTION
**Pull request by nuttycom**
Fixes #1304, #1282, #1238

### CODE REVIEW

File: zcash_client_sqlite/src/wallet/orchard.rs [hunk 1]
```diff
@@ -319,6 +321,27 @@ pub(crate) fn get_orchard_nullifiers(
...
 }
 
+pub(crate) fn detect_spending_accounts<'a>(
+    conn: &Connection,
+    nfs: impl Iterator<Item = &'a Nullifier>,
+) -> Result<HashSet<AccountId>, rusqlite::Error> {
+    let mut account_q = conn.prepare_cached(
+        "SELECT rn.account_id
+        FROM orchard_received_notes rn
+        WHERE rn.nf IN :nf_ptr",
```
Comment (nuttycom) [inline zcash_client_sqlite/src/wallet/orchard.rs:331]: @AArnott one question about this: should an account be detected as funding the transaction even if it's an imported account? Or should this only apply to derived accounts? Same question for Sapling and transparent.

Comment (AArnott) [reply zcash_client_sqlite/src/wallet/orchard.rs:331]: My initial answer is "yes, of course", which makes me wonder if there's a downside that you see that I'm missing. Isn't scanning the same in only requiring the UFVK whether the account is derived or imported? I would expect downloaded or transmitted transactions to be recorded in the db exactly the same whether the account derivation information is in the db or not (as in the imported case).

**Comment by AArnott** [comment]
I applied this change to my branch (combined with your tree panic fix), and early in sync, it failed with:

```
near ":nf_ptr": syntax error in SELECT rn.account_id
        FROM sapling_received_notes rn
        WHERE rn.nf IN :nf_ptr at offset 83
```

**Comment by nuttycom** [comment]
> I applied this change to my branch (combined with your tree panic fix), and early in sync, it failed with:
> 
> ```
> near ":nf_ptr": syntax error in SELECT rn.account_id
>         FROM sapling_received_notes rn
>         WHERE rn.nf IN :nf_ptr at offset 83
> ```

Oops, fixed, thanks.

**Comment by AArnott** [comment]
That's much better. Everything in the sqlite table looks correct now. There is one remaining error in the balance impact calculation for the send-to-self transaction, but I believe that is in my own code.

**Comment by AArnott** [comment]
I just confirmed the remaining discrepancy was in my code and I have a fix for that too. Thanks for fixing this!

File: zcash_client_sqlite/src/wallet/orchard.rs (hunk 1 above)
Comment (str4d) [reply zcash_client_sqlite/src/wallet/orchard.rs]: For imported UFVK accounts, we definitely should do this tracking, because it's just metadata between accounts for which we have complete information. I don't believe we will ever select imported UIVK accounts here, as we don't have nullifier-deriving keys for those accounts, and thus can never populate `rn.nf`.

We should separately ensure that we set the "to account" correctly on the send side for any source account that we would be fetching here (to ensure symmetry in the reported data), but that's likely going to require a migration to the `sent_notes` table (as we currently use the account column there as a proxy for "account-internal send", which would be invalid in this context), so that does not need to happen in this PR (or even in the next release).

File: zcash_client_sqlite/src/lib.rs [hunk 2]
```diff
@@ -1052,8 +1052,16 @@ impl<P: consensus::Parameters> WalletWrite for WalletDb<rusqlite::Connection, P>
     ) -> Result<(), Self::Error> {
         self.transactionally(|wdb| {
             let tx_ref = wallet::put_tx_data(wdb.conn.0, d_tx.tx(), None, None)?;
+            let funding_accounts = wallet::get_funding_accounts(wdb.conn.0, d_tx.tx())?;
+            let funding_account = funding_accounts.iter().next().copied();
+            if funding_accounts.len() > 1 {
+                warn!(
+                    "More than one wallet account detected as funding transaction {:?}, selecting {:?}",
```
Comment (str4d) [inline zcash_client_sqlite/src/lib.rs:1059]: I believe that this behaviour will lead to inconsistent views for the non-selected accounts, in exactly the way that @AArnott originally raised. It won't occur _often_ because multi-account funded transactions should be rare (as the approach is generally frowned upon), but it could happen. I think it's okay to choose this behaviour for now however, because any change we'd make to enable full funding-account tracking would require a database migration, at which point we'd just run `get_funding_accounts` again inside the migration.

Separately, do we need to pair this change with a migration to change how we recorded past notes? AFAICT the change in this PR will only affect future notes in the wallet, and the views will remain invalid for past notes. The data migration in that case would be the same as I mention above (except selecting a single account in the migration), so I think it's fine to omit this change in this PR (as newly recovered-from-seed wallets will be fine with just this change) and then add a migration later. If no migration is added to this PR, open an issue to do so.

File: zcash_client_sqlite/src/lib.rs [hunk 3]
```diff
@@ -1083,18 +1091,26 @@ impl<P: consensus::Parameters> WalletWrite for WalletDb<rusqlite::Connection, P>
...
-                            }
-                            None => {
-                                spending_account_id = Some(*output.account());
-                            }
-                        }
-
                         wallet::sapling::put_received_note(wdb.conn.0, output, tx_ref, None)?;
+
+                        if let Some(account_id) = funding_account {
+                            // Even if the recipient address is external, record the send as internal.
```
Comment (str4d) [inline zcash_client_sqlite/src/lib.rs:1097]: Blocking:

This is the exact misuse of the `sent_notes` account column that I mentioned earlier. The enum is named `WalletInternal`, but prior to now AFAICT this has always been used as "account-internal". Given that _any_ account in the wallet can be the funding account here, "wallet-internal" is ill-defined; the two accounts may have no common controller of spend authority (e.g. not be derived from the same seed). For example, it would make no sense for a note sent from a wallet account to ZecPages to be considered a "wallet-internal" transaction just because the ZecPages full viewing key is imported.

As an additional datapoint for this column currently meaning "account-internal", if we detect a note as going to an external address, and then later call `create_account` such that the external address is learned to actually be a wallet address, we do not update the `sent_notes` table to correct the information.

If we are going to make this change to how funding accounts are tracked, we need to do so in a way that ensures data consistency. That means either writing a migration to distinguish "account-internal" from "wallet-internal" in the `sent_notes` table, or writing a migration to redefine the `to_account_id` column as "amongst the accounts derived within or imported into this wallet database" and add code to rescan the _entire_ wallet to update relationships whenever a new account is created or imported.

File: zcash_client_sqlite/src/lib.rs [hunk 4]
```diff
@@ -1136,50 +1153,69 @@ impl<P: consensus::Parameters> WalletWrite for WalletDb<rusqlite::Connection, P>
...
-                            }
-                            None => {
-                                spending_account_id = Some(*output.account());
-                            }
-                        }
-
                         wallet::orchard::put_received_note(wdb.conn.0, output, tx_ref, None)?;
+
+                        if let Some(account_id) = funding_account {
+                            // Even if the recipient address is external, record the send as internal.
```
Comment (str4d) [inline zcash_client_sqlite/src/lib.rs:1159]: Ditto.

File: zcash_client_sqlite/src/lib.rs [hunk 5]
```diff
@@ -1136,50 +1153,69 @@ impl<P: consensus::Parameters> WalletWrite for WalletDb<rusqlite::Connection, P>
...
-                        .any(|input| nf == input.nullifier())
-                ).map(|(account_id, _)| account_id);
-                #[cfg(not(feature = "orchard"))]
-                let orchard_from_account = None;
+                let funding_accounts = wallet::get_funding_accounts(wdb.conn.0, d_tx.tx())?;
+                let funding_account = funding_accounts.iter().next().copied();
+                if let Some(account_id) = funding_account {
+                    if funding_accounts.len() > 1 {
+                        warn!(
+                            "More than one wallet account detected as funding transaction {:?}, selecting {:?}",
```
Comment (str4d) [inline zcash_client_sqlite/src/lib.rs:1206]: There's a slight difference in the new logic: before if a transaction spent Sapling funds from one account and Orchard funds from another, the correct data would be recorded. Now, one of the accounts will be used for both. This is probably fine for the same reason as above: a future migration could insert the other accounts after changing the tables.

**Review by str4d — CHANGES_REQUESTED** [review]
Reviewed 9b4e9ea10d97594b59f5de355996cdb9cfe8ccdf. The `sent_notes` table migration is blocking, because the data inconsistency introduced in this PR will affect Zashi 1.0; the other comments would not because Zashi 1.0 will not support multiple accounts.

If the `sent_notes` table migration is not feasible on the Zashi 1.0 timeline, then for this PR to be merged as part of Zashi 1.0 the new `WalletInternal` parts must be gated on the wallet only containing a single account (which ensures that the cross-account data inconsistency cannot occur). This restriction could then be lifted in a subsequent post-Zashi-1.0 crate release when the necessary migrations are introduced.

**Review by daira — APPROVED** [review]
utACK; no additional comments beyond @str4d's. Please at least file tickets for remaining issues.

File: zcash_client_sqlite/src/lib.rs (hunk 3 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/lib.rs:1097]: The easy fix here is to restrict this check to verify that the funding account is the receiving account. When I refer to "external" here I'm simply meant the zip32 external scope.

File: zcash_client_sqlite/src/testing/pool.rs [hunk 6]
```diff
@@ -288,6 +293,11 @@ pub(crate) fn send_single_step_proposed_transfer<T: ShieldedPoolTester>() {
 
     let tx_history = st.get_tx_history().unwrap();
     assert_eq!(tx_history.len(), 2);
+
+    assert_matches!(
+        decrypt_and_store_transaction(&st.network(), st.wallet_mut(), &tx),
+        Ok(_)
+    );
```
[the remark this answers is not in the document]
Comment (nuttycom) [reply zcash_client_sqlite/src/testing/pool.rs:300]: It's here to ensure that the view query is valid. When I have more time I will verify the return values.

File: zcash_client_sqlite/src/lib.rs (hunk 3 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/lib.rs:1097]: Wait a minute though, this is just populating the "from_account" column of the sent_notes table correctly; the to_account column should already be getting the correct data. So I don't think there is a problem here at all.

Comment (nuttycom) [reply zcash_client_sqlite/src/lib.rs:1097]: The recipient value being constructed in this fashion ensures that the to_account field gets set correctly. You're correct though that reusing the "WalletInternal" variant in this fashion is a change in semantics. It may be that we just need an additional Recipient variant, that can carry both the address (for external addresses) and the recipient account ID.

File: zcash_client_sqlite/src/lib.rs (hunk 2 above)
Comment (AArnott) [reply zcash_client_sqlite/src/lib.rs:1057]: To be clear, since I don't fully follow @str4d's comment, I don't really care about transactions that are funded from multiple accounts, as to my knowledge no wallet enabled users to do that, so it's unlikely to come up in account recovery scenarios. 
What I _do_ care about is that in a multi-account wallet, transactions are correctly attributed as having been funded by the _one_ account that applies.

File: zcash_client_sqlite/src/lib.rs [hunk 7]
```diff
@@ -1049,19 +1050,28 @@ impl<P: consensus::Parameters> WalletWrite for WalletDb<rusqlite::Connection, P>
...
                             //TODO: Recover the UA, if possible.
                             Recipient::Sapling(output.note().recipient())
                         } else {
-                            Recipient::InternalAccount(
-                                *output.account(),
-                                Note::Sapling(output.note().clone()),
-                            )
+                            Recipient::InternalAccount {
+                                receiving_account: *output.account(),
+                                external_address: None,
```
Comment (str4d) [inline zcash_client_sqlite/src/lib.rs:1072]: How can we ensure this is set correctly for cross-account transfers instead of setting it to `None`?

File: zcash_client_sqlite/src/lib.rs [hunk 8]
```diff
@@ -1075,23 +1085,32 @@ impl<P: consensus::Parameters> WalletWrite for WalletDb<rusqlite::Connection, P>
...
-                            }
-                        }
-
                         wallet::sapling::put_received_note(wdb.conn.0, output, tx_ref, None)?;
+
+                        if let Some(account_id) = funding_account {
+                            let recipient = Recipient::InternalAccount {
+                                receiving_account: *output.account(),
+                                // TODO: recover the actual UA, if possible
+                                external_address: Some(Address::Sapling(output.note().recipient())),
```
Comment (str4d) [inline zcash_client_sqlite/src/lib.rs:1099]: How can we ensure we distinguish between account-internal and cross-account transfers, if we always set `external_address`?

File: zcash_client_sqlite/src/lib.rs [hunk 9]
```diff
@@ -1106,15 +1125,17 @@ impl<P: consensus::Parameters> WalletWrite for WalletDb<rusqlite::Connection, P>
...
+                                PoolType::Shielded(ShieldedProtocol::Orchard),
                             )
                         } else {
-                            Recipient::InternalAccount(
-                                *output.account(),
-                                Note::Orchard(*output.note()),
-                            )
+                            Recipient::InternalAccount {
+                                receiving_account: *output.account(),
+                                external_address: None,
```
Comment (str4d) [inline zcash_client_sqlite/src/lib.rs:1136]: Ditto: how do we ensure this is set correctly for cross-account transfers?

File: zcash_client_sqlite/src/lib.rs [hunk 10]
```diff
@@ -1128,55 +1149,81 @@ impl<P: consensus::Parameters> WalletWrite for WalletDb<rusqlite::Connection, P>
...
+                            // Even if the recipient address is external, record the send as internal.
+                            let recipient = Recipient::InternalAccount {
+                                receiving_account: *output.account(),
+                                // TODO: recover the actual UA, if possible
+                                external_address: Some(Address::Unified(
+                                    UnifiedAddress::from_receivers(
+                                    Some(output.note().recipient()),
+                                    None,
+                                    None,
+                                ).expect("UA has an Orchard receiver by construction."))),
```
Comment (str4d) [inline zcash_client_sqlite/src/lib.rs:1169]: Ditto: how do we distinguish account-internal from cross-account?

**Review by str4d — COMMENTED** [review]
Reviewed as of 151e6e526e52f96f2c686516daf8cc7cecf18c1a

File: zcash_client_sqlite/src/lib.rs (hunk 8 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/lib.rs:1099]: Same answer as above, this is the contract of `TransferType`.

File: zcash_client_sqlite/src/lib.rs (hunk 9 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/lib.rs:1136]: Same, this is down to `TransferType`

File: zcash_client_sqlite/src/lib.rs (hunk 7 above)
Comment (str4d) [reply zcash_client_sqlite/src/lib.rs:1072]: What I mean is, don't we need a separate `TransferType` case to distinguish between wallet-internal (cross-account) and account-internal?

Comment (str4d) [reply zcash_client_sqlite/src/lib.rs:1072]: Oh, I guess that for correct cross-account transfers (i.e. correctly treated as separate accounts, so that each account's external FVK sees the correct view), they should show up here as `TransferType::Outgoing`. In that case, we should have `external_address` available already for cross-account transfers and can set it here?

Comment (str4d) [reply zcash_client_sqlite/src/lib.rs:1072]: Ah, and now going back into the PR diff, we're currently in the `TransferType::WalletInternal` branch. Okay, so the change I think is missing here is that the other side of this branch should be tracking the receiving account for cross-account transfers.

File: zcash_client_sqlite/src/lib.rs (hunk 8 above)
Comment (str4d) [reply zcash_client_sqlite/src/lib.rs:1099]: Here I now agree that this is doing the correct thing.

File: zcash_client_sqlite/src/lib.rs [hunk 11]
```diff
@@ -1049,19 +1050,39 @@ impl<P: consensus::Parameters> WalletWrite for WalletDb<rusqlite::Connection, P>
...
+                    TransferType::Outgoing => {
+                        //TODO: Recover the UA, if possible.
+                        let recipient = Recipient::Sapling(output.note().recipient());
+                        wallet::put_sent_output(
+                            wdb.conn.0,
+                            &wdb.params,
+                            *output.account(),
+                            tx_ref,
+                            output.index(),
+                            &recipient,
```
Comment (str4d) [inline zcash_client_sqlite/src/lib.rs:1074]: Okay, the 3-way match now makes clear that there's an asymmetry currently between `TransferType::Outgoing` and `TransferType::Incoming` when it comes to cross-account transfers. Both will put an entry into `sent_notes`, but only `Incoming` fills in both the funding and receiving accounts; `Outgoing` just sets the funding account but not the receiving account.

In general I think we are "probably okay" here, because we scan with IVKs before OVKs, so in the case of a cross-account transfer we will see `Incoming` here instead of `Outgoing`. However, in the future case of actually supporting imported accounts, there will be a bug here depending on the order in which accounts are imported. `wallet::put_sent_output` overwrites the contents of the `to_account_id` column, so if the receiving account gets handled before the sending account, then the collected data will be erased.

This is not simple to recover from: we cannot fix the data inconsistency in a migration if we don't have the raw transaction (to re-decrypt), and we are not guaranteed to have that if the caller is not running enhancement. So I think there are two possible options here:
- Track the receiving account in `TransferType::Outgoing`, as I had previously suggested.
- Change `wallet::put_sent_output` to not overwrite known `to_account_id` values.

File: zcash_client_sqlite/src/lib.rs (hunk 7 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/lib.rs]: Discussion from offline: the received_notes tables would then duplicate exactly information that's available from the sent_notes table, and such duplication would be a potential source of error. So this should be fine.

**Review by str4d — CHANGES_REQUESTED** [review]
Reviewed 4ba7fbd977c05dd3269ca5f263ca65e3915a7d8c

File: zcash_client_sqlite/src/lib.rs (hunk 7 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/lib.rs]: When we scan, we scan with _all_ of the available IVKs, so in the case of a cross-account transfer it will always be detected as `TransferType::Incoming` and will get handled by that branch, which will correctly find and set the source account. And the `Outgoing` case is already handled correctly.

Comment (str4d) [reply zcash_client_sqlite/src/lib.rs]: There's nothing that guarantees that (from the perspective of an implementation of the `WalletWrite` trait), but I agree that's what the current code does in `zcash_client_backend` which is what callers are most likely using, as I said in my subsequent review. It's just brittle.

File: zcash_client_sqlite/src/lib.rs (hunk 11 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/lib.rs:1074]: I prefer the latter solution, because in general for outgoing transfers we don't know anything about the recipient (and it would be a pain to recover that in the send flow), whereas our usual upsert functionality is to not overwrite known data with nulls.

File: zcash_client_sqlite/src/lib.rs (hunk 2 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/lib.rs:1057]: Oh, also, I had already opened https://github.com/zcash/librustzcash/issues/1305 to track the remaining work here.

File: zcash_client_sqlite/src/lib.rs (hunk 11 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/lib.rs:1074]: Within the lifetime of an a wallet database, I can't see how account IDs could ever become unstable; if you swapped them around, you'd have to update all the foreign keys everywhere and this is no exception.

File: zcash_client_sqlite/src/testing/pool.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (nuttycom) [reply zcash_client_sqlite/src/testing/pool.rs:300]: Opened #1315

**Review by str4d — APPROVED** [review]
utACK 1719b0186cd2accabdf6e8f8058614afe8fe7702. Please open issues for the remaining multi-account comments.
