### PR TITLE
`zcash_client_sqlite` Fix error related to commitment tree frontier insertions.

### LINKED ISSUE #1398: Error in note commitment tree maintenance at the bounds of the chain tip shard.
A Zashi user encountered the following error:

> Error while sending funds: An error occurred in querying or updating a note commitment tree: Unable to compute root; missing values for nodes `[...]` 

where the node in question corresponds to the last level-1 subtree of a `shardtree` shard. 

What happens is this:

We insert the frontier at the start of the block range being inserted. This gives us a `CHECKPOINT` leaf. Then, we insert the subtree fragment covering the range for notes in the subsequent block, which crosses the shard boundary, and then prune checkpoints.

Because the frontier was inserted for a not-yet-scanned block, we don't actually know (at the application level) whether the sibling nodes to the frontier should be pruned; we need to scan the block corresponding to the frontier to determine this. However, in `shardtree`, we don't have any distinction between leaves that were inserted as part of a frontier and leaves that were inserted as part of a scan. And so, `shardtree` is completely willing to prune nodes when we remove the `CHECKPOINT` - nodes that are later discovered to be necessary ommers when we discover our wallet's note at the tip of the blindly-inserted frontier.

The solution is to make the distinction between "known prunable" and "not known to be prunable" in the `Retention` type, and use not-known-prunable retention when inserting frontiers.

### PR DESCRIPTION
**Pull request by nuttycom**
Fixes #1398.

### CODE REVIEW

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 1]
```diff
@@ -1475,4 +1498,307 @@ pub(crate) mod tests {
...
+
+    #[cfg(feature = "orchard")]
+    fn prepare_orchard_block_spanning_test(update_subtree_roots: bool) -> TestState<BlockCache> {
+        // Set up a scanning state such that:
+        // * The wallet birthday is in the shard prior to the chain tip
+        // * The user receives funds in the last complete block in the birthday shard,
+        //   in the last note in that block.
+        // * The next block crosses the shard boundary, with two notes in the prior
+        //   shard and two blocks in the subsequent shard
+        // * An additional 100 blocks are scanned, to ensure that
```
Comment (daira) [inline zcash_client_sqlite/src/wallet/scanning.rs:1510]: Incomplete sentence.

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 2]
```diff
@@ -1475,4 +1498,307 @@ pub(crate) mod tests {
...
+            for c in res.orchard_note_commitments() {
+                final_orchard_tree.append(*c);
+            }
+
+            // one block spanning the shard boundary
+            let (spanning_block_height, res, _) =
+                st.generate_next_block_multi(&vec![fake_output(false); 4]);
+
+            // We only add two note commitments to the Orchard frontier, which should
+            // complete a 2^16 subtree. We can then add that subtree root to the
```
Comment (daira) [inline zcash_client_sqlite/src/wallet/scanning.rs:1599]: Incomplete sentence.

**Review by daira — APPROVED** [review]
utACK with minor comments on comments.

File: zcash_client_sqlite/src/testing/pool.rs [hunk 3]
```diff
@@ -1374,8 +1377,10 @@ pub(crate) fn checkpoint_gaps<T: ShieldedPoolTester>() {
         account.birthday().height() + 10,
         BlockHash([0; 32]),
         &not_our_key,
-        AddressType::DefaultExternal,
-        not_our_value,
+        &[FakeCompactOutput {
+            address_type: AddressType::DefaultExternal,
+            value: not_our_value,
+        }],
```
Comment (str4d) [inline zcash_client_sqlite/src/testing/pool.rs]: You defined a `FakeCompactOutput::new` function, but are not using it here:
```suggestion
        &[FakeCompactOutput::new(
            AddressType::DefaultExternal,
            not_our_value,
        )],
```

EDIT: Looks like this was fixed in the second commit. I'd prefer it to be done in the first commit if you're making other changes to that commit.

File: zcash_client_sqlite/src/testing/pool.rs [hunk 4]
```diff
@@ -1956,8 +1961,10 @@ pub(crate) fn invalid_chain_cache_disconnected<T: ShieldedPoolTester>() {
         disconnect_height,
         BlockHash([1; 32]),
         &dfvk,
-        AddressType::DefaultExternal,
-        NonNegativeAmount::const_from_u64(8),
+        &[FakeCompactOutput {
+            address_type: AddressType::DefaultExternal,
+            value: NonNegativeAmount::const_from_u64(8),
+        }],
```
Comment (str4d) [inline zcash_client_sqlite/src/testing/pool.rs]: Ditto:
```suggestion
        &[FakeCompactOutput::new(
            AddressType::DefaultExternal,
            NonNegativeAmount::const_from_u64(8),
        )],
```

EDIT: Looks like this was fixed in the second commit. I'd prefer it to be done in the first commit if you're making other changes to that commit.

File: zcash_client_sqlite/src/testing.rs [hunk 5]
```diff
@@ -471,8 +471,31 @@ where
...
+        value: NonNegativeAmount,
+    ) -> (BlockHeight, Cache::InsertResult, Fvk::Nullifier) {
+        let pre_activation_block = CachedBlock::none(self.sapling_activation_height() - 1);
+        let prior_cached_block = self.latest_cached_block().unwrap_or(&pre_activation_block);
+        let height = prior_cached_block.height() + 1;
+
+        let (res, nf) = self.generate_block_at(
+            height,
+            prior_cached_block.chain_state.block_hash(),
+            &[FakeCompactOutput::new(fvk, address_type, value)],
```
Comment (str4d) [inline zcash_client_sqlite/src/testing.rs]: This method makes no sense to me. Its name (`generate_next_block_multi`) and documentation indicates that it should include multiple outputs, but its code is identical to `generate_next_block`; the code here explicitly only adds one output. Either fix the method to take multiple outputs, or remove it.

EDIT: Looks like this was fixed in the third commit. This fix should definitely be moved into the second commit, as otherwise that commit makes no sense.

File: zcash_client_backend/src/data_api/chain.rs [hunk 6]
```diff
@@ -188,6 +188,10 @@ pub struct CommitmentTreeRoot<H> {
 
 impl<H> CommitmentTreeRoot<H> {
     /// Construct a new `CommitmentTreeRoot` from its constituent parts.
+    ///
+    /// - subtree_end_height The height of the block that produced the note commitment that
+    ///   completed the subtree.
+    /// - root_hash The Merkle root of the completed subtree.
```
Comment (str4d) [inline zcash_client_backend/src/data_api/chain.rs:194]:
```suggestion
    /// - `subtree_end_height`: The height of the block containing the note commitment that
    ///   completed the subtree.
    /// - `root_hash`: The Merkle root of the completed subtree.
```

File: zcash_client_sqlite/src/testing.rs [hunk 7]
```diff
@@ -1938,22 +1937,62 @@ impl BlockCache {
...
 
+pub(crate) struct NoteCommitments {
+    sapling_note_commitments: Vec<sapling::Node>,
+    #[cfg(feature = "orchard")]
+    orchard_note_commitments: Vec<MerkleHashOrchard>,
+}
+
+impl NoteCommitments {
+    #[allow(dead_code)]
+    pub(crate) fn sapling_note_commitments(&self) -> &[sapling::Node] {
```
Comment (str4d) [inline zcash_client_sqlite/src/testing.rs:1932]: The type is already called `NoteCommitments`, so just name this method `NoteCommitments::sapling`:
```suggestion
    pub(crate) fn sapling(&self) -> &[sapling::Node] {
```

File: zcash_client_sqlite/src/testing.rs [hunk 8]
```diff
@@ -1938,22 +1937,62 @@ impl BlockCache {
...
+        self.sapling_note_commitments.as_ref()
+    }
+
+    #[cfg(feature = "orchard")]
+    pub(crate) fn orchard_note_commitments(&self) -> &[MerkleHashOrchard] {
```
Comment (str4d) [inline zcash_client_sqlite/src/testing.rs:1937]: Ditto:
```suggestion
    pub(crate) fn orchard(&self) -> &[MerkleHashOrchard] {
```

File: zcash_client_sqlite/src/testing.rs [hunk 9]
```diff
@@ -1938,22 +1937,62 @@ impl BlockCache {
...
+        self.orchard_note_commitments.as_ref()
+    }
+}
+
 impl TestCache for BlockCache {
     type BlockSource = BlockDb;
-    type InsertResult = ();
+    type InsertResult = NoteCommitments;
```
Comment (str4d) [inline zcash_client_sqlite/src/testing.rs:1944]: Why are we only returning `NoteCommitments` from `impl TestCache for BlockCache`, and not `impl TestCache for FsBlockCache`?

Also, why is this even necessary? `TestCache::insert` takes a `&CompactBlock`, so the caller still has the block and can fetch these commitments from it directly (e.g. with the `NoteCommitments::from_compact_block` constructor I suggest below, or by us adding a helper method to `CompactBlock` in `zcash_client_backend/src/proto.rs`).

File: zcash_client_sqlite/src/testing.rs [hunk 10]
```diff
@@ -1938,22 +1937,62 @@ impl BlockCache {
...
+            orchard_note_commitments: cb
+                .vtx
+                .iter()
+                .flat_map(|tx| {
+                    tx.actions
+                        .iter()
+                        .map(|act| MerkleHashOrchard::from_cmx(&act.cmx().unwrap()))
+                })
+                .collect(),
+        };
```
Comment (str4d) [inline zcash_client_sqlite/src/testing.rs:1972]: Move this into a private constructor `NoteCommitments::from_compact_block` (enabling its reuse as necessary), or move its parts onto `CompactBlock` itself and remove `NoteCommitments`.

**Review by str4d — CHANGES_REQUESTED** [review]
Partial review of 349722aefe4d905314ead4028b283f1ac2252d8a. I have not reviewed the new test, the bugfix, or the clippy lint fixes.

File: zcash_client_sqlite/src/testing.rs (hunk 9 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/testing.rs:1944]: `InsertResult` for `FsBlockCache` was already returning `BlockMeta` and I saw no reason to change it, because all of the relevant tests are just using `BlockCache`.

**Comment by nuttycom** [comment]
[force-pushed](https://github.com/zcash/librustzcash/compare/349722aefe4d905314ead4028b283f1ac2252d8a..62f3abf300c856fe0bc95c2e538b542387b26db8) to address comments from code review.

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 11]
```diff
@@ -1481,4 +1492,307 @@ pub(crate) mod tests {
...
+                                .value()
+                                .unwrap()
+                                .root(Some(Level::from(16))),
+                        )],
+                    )
+                    .unwrap();
+            }
+
+            // Add blocks up to the current chain tip.
+            for _ in 12..123 {
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet/scanning.rs:1624]: This starting at 12 is confusing to me. AFAICT it's meant to indicate the block height offset relative to the birthday height (given how `final_orchard_tree` is mutated), but there's an off-by-one error here (13 blocks are generated prior to this point). Perhaps this is the source of the 111-block bug I mentioned above?

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 12]
```diff
@@ -1481,4 +1492,307 @@ pub(crate) mod tests {
...
+        let new_tip = birthday.height() + 123;
+        st.wallet_mut().update_chain_tip(new_tip).unwrap();
+
+        // Verify that the suggested scan ranges includes only the chain-tip range with ChainTip
+        // priority, and that the range from the wallet birthday to the end of the birthday shard
+        // has Historic priority.
+        let birthday_height = birthday.height().into();
+        let expected = vec![
+            scan_range(
+                (birthday_height + 12)..(new_tip + 1).into(),
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet/scanning.rs:1652]: How should this 12 correspond to the (possibly-erroneous) 12 in `prepare_orchard_block_spanning_test`? As in an earlier comment, a diagram of how the chain is being set up would be helpful.

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 13]
```diff
@@ -1481,4 +1492,307 @@ pub(crate) mod tests {
...
+            &GreedyInputSelector::new(change_strategy, DustOutputPolicy::default());
+
+        let proposal = st.propose_transfer(
+            account.account_id(),
+            input_selector,
+            request,
+            NonZeroU32::new(10).unwrap(),
+        );
+
+        assert_matches!(proposal, Err(_));
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet/scanning.rs:1803]: Would it also be useful to test that after scanning the spanning block, we can make a proposal?

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 14]
```diff
@@ -1481,4 +1492,307 @@ pub(crate) mod tests {
...
+        let new_tip = birthday.height() + 123;
+        st.wallet_mut().update_chain_tip(new_tip).unwrap();
+
+        // Verify that the suggested scan ranges includes only the chain-tip range with ChainTip
+        // priority, and that the range from the wallet birthday to the end of the birthday shard
+        // has Historic priority.
+        let birthday_height = birthday.height().into();
+        let expected = vec![
+            scan_range(
+                birthday_height..(new_tip + 1).into(),
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet/scanning.rs:1743]: This range not being split in two is clearly due to not updating the subtree roots in `prepare_orchard_block_spanning_test`, but it's not clear to me why this is necessary in addition to skipping the spanning block (to provoke the error), and why the other two possible combinations are not tested. While my earlier comment about documenting `prepare_orchard_block_spanning_test` would help, a comment here (or in `orchard_block_spanning_tip_boundary`, wherever is clearer) would also be useful.

File: zcash_client_sqlite/src/wallet/commitment_tree.rs [hunk 15]
```diff
@@ -1010,17 +1010,11 @@ pub(crate) fn put_shard_roots<
...
-                    LevelShifter(r.root_hash().clone()),
-                    Retention::Checkpoint {
-                        id: (),
-                        is_marked: false,
-                    },
-                )
-            }),
+            roots
+                .iter()
+                .map(|r| (LevelShifter(r.root_hash().clone()), Retention::Reference)),
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet/commitment_tree.rs:1017]: Does the fact that we no longer checkpoint in the cap tree matter for backwards compatibility (serialization or otherwise)?

File: zcash_client_sqlite/src/wallet/init/migrations/shardtree_support.rs [hunk 16]
```diff
@@ -173,7 +173,7 @@ impl<P: consensus::Parameters> RusqliteMigration for Migration<P> {
                                 nonempty_frontier.clone(),
                                 Retention::Checkpoint {
                                     id: block_height,
-                                    is_marked: false,
+                                    marking: Marking::Reference,
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet/init/migrations/shardtree_support.rs:176]: This change will only affect unmigrated DBs. It is a correct change to the migration, but (separately from this particular migration) is there any reasonable way to detect frontiers that were already inserted into the tree that have this issue (such as the ones that led to the bug report this PR is addressing)? Or will affected users need to recover from seed?

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 17]
```diff
@@ -1501,7 +1507,8 @@ pub(crate) mod tests {
         //   in the last note in that block.
         // * The next block crosses the shard boundary, with two notes in the prior
         //   shard and two blocks in the subsequent shard
-        // * An additional 100 blocks are scanned, to ensure that
+        // * An additional 100 blocks are scanned, to ensure that the checkpoint
+        //   is pruned.
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet/scanning.rs:1511]: Nit: this change, and the two below it, can safely be moved to the third commit that added the test (as they are not changes forced by the `shardtree` bump).

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 18]
```diff
@@ -791,46 +791,65 @@ pub(crate) mod tests {
...
-
+            .with_initial_chain_state(|rng, network| {
                 // We set the Sapling and Orchard frontiers at the birthday height to be
                 // 1234 notes into the second shard.
                 let frontier_position = Position::from((0x1 << 16) + 1234);
-                let birthday_height =
-                    network.activation_height(NetworkUpgrade::Nu5).unwrap() + birthday_offset;
+                let initial_shard_end =
+                    network.activation_height(NetworkUpgrade::Nu5).unwrap() + initial_shard_blocks;
+                let birthday_height = initial_shard_end + birthday_offset;
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet/scanning.rs:807]: Document on `test_with_nu5_birthday_offset` that `birthday_offset` is an offset from `initial_shard_blocks`, as this is a semantic change to the function argument. Also document that `initial_shard_blocks` is an offset from NU5.

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 19]
```diff
@@ -791,46 +791,65 @@ pub(crate) mod tests {
     }
 
     pub(crate) fn test_with_nu5_birthday_offset<T: ShieldedPoolTester>(
+        initial_shard_blocks: u32,
         birthday_offset: u32,
         prior_block_hash: BlockHash,
+        insert_prior_roots: bool,
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet/scanning.rs:797]: Document what this does and in what kind of tests it should be used.

**Review by str4d — CHANGES_REQUESTED** [review]
Reviewed 62f3abf300c856fe0bc95c2e538b542387b26db8

File: zcash_client_sqlite/src/testing.rs [hunk 20]
```diff
@@ -528,8 +527,7 @@ where
         height: BlockHeight,
         prev_hash: BlockHash,
         fvk: &Fvk,
-        req: AddressType,
-        value: NonNegativeAmount,
+        outputs: &[FakeCompactOutput],
```
[the remark this answers is not in the document]
Comment (str4d) [reply zcash_client_sqlite/src/testing.rs]: AFAICT this is still unresolved (the documentation for `generate_block_at` is now wrong).

File: zcash_client_sqlite/src/wallet/init/migrations/shardtree_support.rs (hunk 16 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/wallet/init/migrations/shardtree_support.rs:176]: The affected users will need to recover from seed, but due to the nature of the bug there should be very few affected users.

File: zcash_client_sqlite/src/wallet/commitment_tree.rs (hunk 15 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/wallet/commitment_tree.rs:1017]: It shouldn't. Checkpoint retention was possibly actually a bug, because it implied that pruning was permitted within the cap, which shouldn't be allowed to happen (it's not a correctness problem, because the cap nodes can always be recomputed, but losing that caching kind of defeats the purpose of the cap.)

File: zcash_client_sqlite/src/wallet/scanning.rs (hunk 14 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/wallet/scanning.rs:1743]: This test does not actually reproduce the error; I added it as an initial attempt to reproduce, and then decided that it was useful independently and so decided to keep it. I can split it out of this PR, but it's closely related to the behavior under test (for obvious reasons) so I thought it kind of made sense to keep here?

File: zcash_client_sqlite/src/wallet/scanning.rs (hunk 12 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/wallet/scanning.rs:1652]: `birthday_height + 12` is the height of the block that spans the shard boundary. Remember that the birthday height is the height of the first block that may contain wallet funds, not the maximum height known _not_ to contain wallet funds. So the birthday block is the first of the 11 blocks initially generated.

**Comment by nuttycom** [comment]
[force-pushed](https://github.com/zcash/librustzcash/compare/62f3abf300c856fe0bc95c2e538b542387b26db8..e3956c325155d73a469f8fd59730f6ce40668269?w=1) to address comments from review.

File: zcash_client_backend/src/serialization/shardtree.rs [hunk 21]
```diff
@@ -43,6 +44,10 @@ pub fn write_shard<H: HashSer, W: Write>(writer: &mut W, tree: &PrunableTree<H>)
                 writer.write_u8(NIL_TAG)?;
                 Ok(())
             }
+            Node::Pruned => {
+                writer.write_u8(PRUNED_TAG)?;
+                Ok(())
```
Comment (daira) [inline zcash_client_backend/src/serialization/shardtree.rs:49]: This will not be readable by prior implementations of `read_shard_v1`. Should the version number be bumped, or would that just cause more problems?

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 22]
```diff
@@ -1475,4 +1508,352 @@ pub(crate) mod tests {
         let actual = suggest_scan_ranges(&st.wallet().conn, Ignored).unwrap();
         assert_eq!(actual, expected);
     }
+
+    /// This tests the case wherein:
+    /// * The wallet birthday is in the shard prior to the chain tip
+    /// * The user receives funds in the last complete block in the birthday shard,
+    ///   in the last note in that block.
+    /// * The next block crosses the shard boundary, with two notes in the prior
+    ///   shard and two blocks in the subsequent shard
```
Comment (daira) [inline zcash_client_sqlite/src/wallet/scanning.rs:1517]:
```suggestion
    ///   shard and two notes in the subsequent shard.
```

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 23]
```diff
@@ -1475,4 +1508,352 @@ pub(crate) mod tests {
...
+            // root of the completed subtree.
+            for c in res.orchard().iter().take(2) {
+                final_orchard_tree.append(*c);
+            }
+
+            assert_eq!(final_orchard_tree.tree_size(), 0x1 << 17);
+            assert_eq!(spanning_block_height, birthday.height() + 12);
+
+            // Insert the root of the completed subtree if `with_birthday_subtree_root` is set.
+            // This simulates the situation where the subtree roots have all bee inserted prior
```
Comment (daira) [inline zcash_client_sqlite/src/wallet/scanning.rs:1641]:
```suggestion
            // This simulates the situation where the subtree roots have all been inserted prior
```

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 24]
```diff
@@ -1475,4 +1508,352 @@ pub(crate) mod tests {
...
+        let new_tip = birthday.height() + 122;
+        st.wallet_mut().update_chain_tip(new_tip).unwrap();
+
+        // Verify that the suggested scan ranges includes only the chain-tip range with ChainTip
+        // priority, and that the range from the wallet birthday to the end of the birthday shard
+        // has Historic priority.
+        let birthday_height = birthday.height().into();
+        let expected = vec![
+            scan_range(
+                (birthday_height + 12)..(new_tip + 1).into(),
```
Comment (daira) [inline zcash_client_sqlite/src/wallet/scanning.rs:1691]:
```suggestion
                (birthday_height + 12)..=new_tip.into(),
```
Non-blocking.

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 25]
```diff
@@ -1475,4 +1508,352 @@ pub(crate) mod tests {
...
+        let new_tip = birthday.height() + 122;
+        st.wallet_mut().update_chain_tip(new_tip).unwrap();
+
+        // Verify that the suggested scan ranges includes only the chain-tip range with ChainTip
+        // priority, and that the range from the wallet birthday to the end of the birthday shard
+        // has Historic priority.
+        let birthday_height = birthday.height().into();
+        let expected = vec![
+            scan_range(
+                birthday_height..(new_tip + 1).into(),
```
Comment (daira) [inline zcash_client_sqlite/src/wallet/scanning.rs:1784]:
```suggestion
                birthday_height..=new_tip.into(),
```
Non-blocking.

**Review by daira — DISMISSED** [review]
utACK

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 26]
```diff
@@ -1475,4 +1508,352 @@ pub(crate) mod tests {
         let actual = suggest_scan_ranges(&st.wallet().conn, Ignored).unwrap();
         assert_eq!(actual, expected);
     }
+
+    /// This tests the case wherein:
```
Comment (nuttycom) [inline zcash_client_sqlite/src/wallet/scanning.rs:1512]:
```suggestion
    /// This sets up the case wherein:
```

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 27]
```diff
@@ -1475,4 +1508,352 @@ pub(crate) mod tests {
...
+    ///   shard and two blocks in the subsequent shard
+    /// * An additional 110 blocks are scanned, to ensure that the checkpoint
+    ///   is pruned.
+    ///
+    /// The diagram below shows the arrangement. the position of the X indicates the
+    /// note commitment for the note belonging to our wallet.
+    /// ```
+    /// blocks:      |<---- 5000 ---->|<----- 10 ---->|<--- 11 --->|<- 1  ->|<- 1 ->|<----- 110 ----->|
+    ///       nu5_activation                       birthday                                       chain_tip
+    /// commitments: |<---- 2^16 ---->|<--(2^16-50)-->|<--- 44 --->|<-___X->|<- 4 ->|<----- 114 ------|
```
Comment (nuttycom) [inline zcash_client_sqlite/src/wallet/scanning.rs:1526]:
```suggestion
    /// commitments: |<---- 2^16 ---->|<--(2^16-50)-->|<--- 44 --->|<-___X->|<- 4 ->|<----- 110 ------|
```

File: zcash_client_backend/src/serialization/shardtree.rs (hunk 21 above)
Comment (nuttycom) [reply zcash_client_backend/src/serialization/shardtree.rs:49]: I think this is fine; we can treat version changes that are backwards-compatible as part of the same version.

**Review by str4d — APPROVED** [review]
utACK 0c1ac8a629aaa4a9d8fe95460a3965554ee4d8d9

**Review by str4d — APPROVED** [review]
Re-utACK 3e090dca6695040b1a446c130b864f230a3e8408

**Review by daira — COMMENTED** [review]
Post-hoc ACK
