### PR TITLE
get_transparent_balances fails with `no such column`

### LINKED ISSUE #686: get_transparent_balances fails with `no such column`
get_transparent_balances
"Error while fetching transparent balances for AccountId(0): no such column: u.received_by_accountt"

### PR DESCRIPTION
**Pull request by pacu**
Error message:

"Error while fetching transparent balances for AccountId(0): no such column: u.received_by_accountt"

Closes #686

### CODE REVIEW

File: zcash_client_sqlite/src/wallet.rs [hunk 1]
```diff
@@ -1006,7 +1006,7 @@ pub(crate) fn get_unspent_transparent_outputs<P: consensus::Parameters>(
 /// such that the block that included the transaction was mined at a height less than or equal to
 /// the provided `max_height`.
 #[cfg(feature = "transparent-inputs")]
-pub(crate) fn get_transparent_balances<P: consensus::Parameters>(
+pub(crate) fn 686<P: consensus::Parameters>(
```
Comment (nuttycom) [inline zcash_client_sqlite/src/wallet.rs:1009]: What's going on here???

Comment (pacu) [reply zcash_client_sqlite/src/wallet.rs:1009]: thanks Visual Studio Code ❤️

**Review by nuttycom — APPROVED** [review]
utACK
