### PR TITLE
Gracefully handle when given an Orchard-only UA

### LINKED ISSUE #1008: Transaction builder should fail gracefully when given an Orchard-only UA
https://github.com/zcash/librustzcash/blob/main/zcash_client_backend/src/data_api/wallet.rs#L551 is a TODO that was left incomplete at some point, that was intended to be fixed before SDK 2.0 release. It needs to be fixed with high priority.

Until Orchard support is implemented, this should cause a graceful failure rather than a panic.

### PR DESCRIPTION
**Pull request by tw0po1nt**
Closes #1008

### CODE REVIEW

File: zcash_client_backend/src/data_api/error.rs [hunk 1]
```diff
@@ -54,6 +54,9 @@ pub enum Error<DataSourceError, CommitmentTreeError, SelectionError, FeeError, N
     /// It is forbidden to provide a memo when constructing a transparent output.
     MemoForbidden,
 
+    /// Attempted to create a spend to an unsupported output type (i.e. Orchard)
+    UnsupportedOutputType,
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/error.rs:58]: This should wrap a `PoolType` so that the  user can observe the failure.

File: zcash_client_backend/src/data_api/wallet.rs [hunk 2]
```diff
@@ -546,12 +546,26 @@ where
...
                     .as_ref()
                     .map_or_else(MemoBytes::empty, |m| m.clone());
-                builder.add_sapling_output(
-                    external_ovk,
-                    *ua.sapling().expect("TODO: Add Orchard support to builder"),
-                    payment.amount,
-                    memo.clone(),
-                )?;
+
+                if ua.sapling().is_some() {
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/wallet.rs:550]:
```suggestion
                if let Some(sapling_receiver) = ua.sapling() {
```

File: zcash_client_backend/src/data_api/wallet.rs [hunk 3]
```diff
@@ -546,12 +546,26 @@ where
...
+                    builder.add_sapling_output(
+                        external_ovk,
+                        *ua.sapling().unwrap(),
+                        payment.amount,
+                        memo.clone(),
+                    )?;
+                } else if ua.transparent().is_some() {
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/wallet.rs:557]:
```suggestion
                } else if let Some(taddr) = ua.transparent() {
```

File: zcash_client_backend/src/data_api/wallet.rs [hunk 4]
```diff
@@ -546,12 +546,26 @@ where
...
-                    external_ovk,
-                    *ua.sapling().expect("TODO: Add Orchard support to builder"),
-                    payment.amount,
-                    memo.clone(),
-                )?;
+
+                if ua.sapling().is_some() {
+                    builder.add_sapling_output(
+                        external_ovk,
+                        *ua.sapling().unwrap(),
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/wallet.rs:553]:
```suggestion
                        sapling_reciever,
```
(may require a `*`, can't tell from here)

File: zcash_client_backend/src/data_api/wallet.rs [hunk 5]
```diff
@@ -546,12 +546,26 @@ where
...
+                        payment.amount,
+                        memo.clone(),
+                    )?;
+                } else if ua.transparent().is_some() {
+                    if payment.memo.is_some() {
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/wallet.rs:558]: I wonder if we should even check the transparent receiver if a memo is provided. This error message could be misleading if someone provided an Orchard+Transparent uaddr; I feel like the error needs to somehow communicate that this error is occurring because we're falling back to the transparent receiver. 

We should at least document this behavior. It also points to a potential issue in the UI; the front end needs to check up front whether it can send a memo to a given uaddr before it decides whether to expose the ability to enter a memo. I think that this issue is what Zooko was referring to with this ticket: https://github.com/zcash/librustzcash/issues/910

File: zcash_client_backend/src/data_api/wallet.rs [hunk 6]
```diff
@@ -546,12 +546,26 @@ where
...
+                        return Err(Error::MemoForbidden);
+                    } else {
+                        builder.add_transparent_output(
+                            ua.transparent().unwrap(),
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/wallet.rs:562]:
```suggestion
                            taddr, 
```

File: zcash_client_backend/src/data_api/error.rs (hunk 1 above)
Comment (nuttycom) [reply zcash_client_backend/src/data_api/error.rs:58]: Also, this addition will need to be documented in `zcash_client_backend/CHANGELOG.md`

**Review by nuttycom — COMMENTED** [review]
This is looking really good! There are a couple of documentation changes/additions that will be needed, and a couple of small stylistic suggestions.

File: zcash_client_backend/src/data_api/error.rs [hunk 7]
```diff
@@ -54,6 +54,9 @@ pub enum Error<DataSourceError, CommitmentTreeError, SelectionError, FeeError, N
     /// It is forbidden to provide a memo when constructing a transparent output.
     MemoForbidden,
 
+    /// Attempted to create a spend to an unsupported output type (i.e. Orchard)
```
Comment (daira) [inline zcash_client_backend/src/data_api/error.rs:57]:
```suggestion
    /// Attempted to create a spend to an unsupported output type (currently, Orchard).
```

File: zcash_client_backend/src/data_api/wallet.rs (hunk 5 above)
Comment (tw0po1nt) [reply zcash_client_backend/src/data_api/wallet.rs:558]: I think, per the discussion in that thread, we should just document this behavior for now.

**Review by tw0po1nt — COMMENTED** [review]
Self-reviewed latest changes

File: zcash_client_backend/src/data_api/error.rs [hunk 8]
```diff
@@ -22,7 +22,7 @@ use zcash_primitives::{legacy::TransparentAddress, zip32::DiversifierIndex};
 
 /// Errors that can occur as a consequence of wallet operations.
 #[derive(Debug)]
-pub enum Error<DataSourceError, CommitmentTreeError, SelectionError, FeeError, NoteRef> {
+pub enum Error<DataSourceError, CommitmentTreeError, SelectionError, FeeError, NoteRef, PoolType> {
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/error.rs:25]: `PoolType` doesn't need to be a type parameter here; it can be a concrete type.;

**Review by nuttycom — CHANGES_REQUESTED** [review]

File: zcash_client_backend/CHANGELOG.md [hunk 9]
```diff
@@ -7,6 +7,11 @@ and this library adheres to Rust's notion of
 
 ## [Unreleased]
 
+### Added
+- `zcash_client_backend::data_api::ShieldedProtocol` has a new variant for `Orchard`, allowing for better reporting to callers trying to perform actions using `Orchard` before it is fully supported.
```
Comment (daira) [inline zcash_client_backend/CHANGELOG.md:11]:
```suggestion
- `zcash_client_backend::data_api::ShieldedProtocol` has a new variant for `Orchard`,
  allowing for better reporting to callers trying to perform actions using `Orchard`
  before it is fully supported.
```
(The rest of the doc is line-wrapped.)

File: zcash_client_backend/src/data_api.rs [hunk 10]
```diff
@@ -556,7 +556,8 @@ pub struct SentTransaction<'a> {
 pub enum ShieldedProtocol {
     /// The Sapling protocol
     Sapling,
-    // TODO: Orchard
+    /// The Orchard protocol
+    Orchard
```
Comment (daira) [inline zcash_client_backend/src/data_api.rs:560]:
```suggestion
    Orchard,
```

Comment (nuttycom) [reply zcash_client_backend/src/data_api.rs:560]: This should be fixed by a `cargo fmt`

File: zcash_client_backend/src/data_api/wallet.rs [hunk 11]
```diff
@@ -546,12 +549,26 @@ where
...
+                        builder.add_transparent_output(
+                            taddr, 
+                            payment.amount
+                        )?;
+                    }
+                } else {
+                    return Err(Error::UnsupportedPoolType(PoolType::Shielded(ShieldedProtocol::Orchard)));
+                }
                 sapling_output_meta.push((
                     Recipient::Unified(ua.clone(), PoolType::Shielded(ShieldedProtocol::Sapling)),
```
Comment (daira) [inline zcash_client_backend/src/data_api/wallet.rs:573]: This is incorrect if we took the `builder.add_transparent_output(...)` branch above. Blocking.

**Review by nuttycom — DISMISSED** [review]
utACK modulo the changelog formatting and `rustfmt` failures.

File: zcash_client_sqlite/src/wallet.rs [hunk 12]
```diff
@@ -758,7 +759,12 @@ pub(crate) fn get_received_memo(
     conn: &rusqlite::Connection,
     note_id: NoteId,
 ) -> Result<Option<Memo>, SqliteClientError> {
-    let memo_bytes: Option<Vec<_>> = match note_id.protocol() {
+    let protocol = note_id.protocol();
+    if let ShieldedProtocol::Orchard = protocol {
+        return Err(SqliteClientError::UnsupportedPoolType(PoolType::Shielded(protocol)));
+    }
+
+    let memo_bytes: Option<Vec<_>> = match protocol {
```
Comment (daira) [inline zcash_client_sqlite/src/wallet.rs:767]: I prefer this:
```suggestion
    let memo_bytes: Option<Vec<_>> = match note_id.protocol {
        ShieldedProtocol::Orchard => {
            return Err(SqliteClientError::UnsupportedPoolType(PoolType::Shielded(protocol)));
        },
```

Comment (daira) [inline zcash_client_sqlite/src/wallet.rs:767]: I prefer this:
```suggestion
    let memo_bytes: Option<Vec<_>> = match protocol {
        ShieldedProtocol::Orchard => {
            return Err(SqliteClientError::UnsupportedPoolType(PoolType::Shielded(protocol)));
        },
```

**Review by daira — CHANGES_REQUESTED** [review]
This comment is blocking: https://github.com/zcash/librustzcash/pull/1009/files#r1350429559

**Comment by tw0po1nt** [comment]
@daira @nuttycom Fixed the merge conflicts, this should be ready for re-review

**Review by nuttycom — APPROVED** [review]
utACK https://github.com/zcash/librustzcash/pull/1009/commits/a788cc4c4dc03b4e6a0c0f592c7fbf6329f7f512

**Review by daira — APPROVED** [review]
utACK
