### PR TITLE
kind::unified: Extract common unified encoding logic.

### LINKED ISSUE #342: Build failure in bitvec
On a clean build, I get several instances of this error:

```
error[E0034]: multiple applicable items in scope
   --> /home/hanh/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.18.4/src/field.rs:307:25
    |
307 |         check("load", len, M::BITS);
    |                               ^^^^ multiple `BITS` found
    |
note: candidate #1 is defined in the trait `mem::BitMemory`
   --> /home/hanh/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.18.4/src/mem.rs:26:2
    |
26  |     const BITS: u8 = mem::size_of::<Self>() as u8 * 8;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `funty::IsNumber`
   --> /home/hanh/.cargo/registry/src/github.com-1ecc6299db9ec823/funty-1.2.0/src/lib.rs:144:2
    |
144 |     const BITS: u32;
    |     ^^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #1
    |
307 |         check("load", len, mem::BitMemory::BITS);
    |                            ^^^^^^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #2
    |
307 |         check("load", len, funty::IsNumber::BITS);
    |                            ^^^^^^^^^^^^^^^^^^^^^
307 |         check("load", len, mem::BitMemory::BITS);
    |                            ^^^^^^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #2
    |
307 |         check("load", len, funty::IsNumber::BITS);
    |                            ^^^^^^^^^^^^^^^^^^^^^
```

To reproduce, just clone the repo and run cargo build.

### PR DESCRIPTION
**Pull request by therealyingtong**
Part of #372.

Co-authored-by: Jack Grigg <jack@electriccoin.co>

### CODE REVIEW

File: components/zcash_address/src/kind/unified.rs [hunk 1]
```diff
@@ -138,82 +141,36 @@ impl fmt::Display for ParseError {
...
-    fn addr(&self) -> &[u8] {
-        match self {
-            Receiver::P2pkh(data) => data,
-            Receiver::P2sh(data) => data,
-            Receiver::Sapling(data) => data,
-            Receiver::Orchard(data) => data,
-            Receiver::Unknown { data, .. } => data,
-        }
+    pub trait Sealed {
+        type Receiver: Receiver;
```
Comment (str4d) [inline components/zcash_address/src/kind/unified.rs:157]: Conversely, I think this associated type needs to be unsealed and on the `Unified` trait, otherwise the caller has no way to _use_ the output of the public methods on `Unified` that return receivers unless you know the concrete type. Though maybe that's desired?

File: components/zcash_address/src/kind/unified.rs [hunk 2]
```diff
@@ -138,82 +141,36 @@ impl fmt::Display for ParseError {
...
-    fn typecode(&self) -> Typecode {
-        match self {
-            Receiver::P2pkh(_) => Typecode::P2pkh,
-            Receiver::P2sh(_) => Typecode::P2sh,
-            Receiver::Sapling(_) => Typecode::Sapling,
-            Receiver::Orchard(_) => Typecode::Orchard,
-            Receiver::Unknown { typecode, .. } => Typecode::Unknown(*typecode),
-        }
+    /// A raw address or viewing key.
+    pub trait Receiver:
```
Comment (str4d) [inline components/zcash_address/src/kind/unified.rs:149]:
```suggestion
    pub trait SealedReceiver:
```

File: components/zcash_address/src/kind/unified.rs [hunk 3]
```diff
@@ -138,82 +141,36 @@ impl fmt::Display for ParseError {
...
+        TryFrom<(u32, Vec<u8>), Error = ParseError> + cmp::Ord + cmp::PartialOrd + Clone
```
Comment (str4d) [inline components/zcash_address/src/kind/unified.rs:150]: Is this what motivated the change to the `TryFrom` impl on `Receiver`? This would be clearer if the PR were split into three commits as above.

File: components/zcash_address/src/kind/unified.rs [hunk 4]
```diff
@@ -299,19 +252,17 @@ impl TryFrom<Vec<Receiver>> for Address {
...
+            Ok(Self::from_inner(receivers))
         }
     }
-}
 
-impl Address {
-    /// Returns the raw encoding of this Unified Address.
-    pub(crate) fn to_bytes(&self, hrp: &str) -> Vec<u8> {
+    /// Returns the raw encoding of this Unified Address or viewing key.
+    fn to_bytes(&self, hrp: &str) -> Vec<u8> {
```
Comment (str4d) [inline components/zcash_address/src/kind/unified.rs:260]: Hmm, this was previously an internal method, and now it is exposed publicly. I'd prefer that it be placed on `Sealed`.

**Review by str4d — CHANGES_REQUESTED** [review]

**Comment by therealyingtong** [comment]
[Force-pushed](https://github.com/zcash/librustzcash/compare/64e5ac539cac0330cf5eb950c1fc88abcc632f3d..e72eddb59a3db78f557f89b500f41d94a6d40587) to split into three smaller commits, as suggested in https://github.com/zcash/librustzcash/pull/460#discussion_r756219808.

File: components/zcash_address/src/kind/unified/address.rs [hunk 5]
```diff
@@ -0,0 +1,320 @@
...
+impl cmp::PartialOrd for Receiver {
+    fn partial_cmp(&self, other: &Self) -> Option<cmp::Ordering> {
+        Some(self.cmp(other))
+    }
+}
+
+impl TryFrom<(u32, Vec<u8>)> for Receiver {
+    type Error = ParseError;
+
+    fn try_from((typecode, addr): (u32, Vec<u8>)) -> Result<Self, Self::Error> {
```
[the remark this answers is not in the document]
Comment (therealyingtong) [reply components/zcash_address/src/kind/unified/address.rs]: This has now been un-altered.

File: components/zcash_address/src/kind/unified.rs [hunk 6]
```diff
@@ -3,27 +3,11 @@ use std::collections::HashSet;
...
-/// The HRP for a Bech32m-encoded testnet Unified Address.
-///
-/// Defined in [ZIP 316][zip-0316].
-///
-/// [zip-0316]: https://zips.z.cash/zip-0316
-pub(crate) const TESTNET: &str = "utest";
-
-/// The HRP for a Bech32m-encoded regtest Unified Address.
-pub(crate) const REGTEST: &str = "uregtest";
+pub(crate) use address::Address;
```
Comment (nuttycom) [inline components/zcash_address/src/kind/unified.rs:10]: Why is this `pub(crate)` instead of `pub`? The `Address` type is needed in the zcashd ffi, and I don't see how to get to it.

Comment (str4d) [reply components/zcash_address/src/kind/unified.rs:10]: Yeah, these types were previously visible in this module. I think both `Address` and `Receiver` should be `pub use`d here to retain their previous visibility.

File: components/zcash_address/src/kind/unified.rs [hunk 7]
```diff
@@ -138,82 +122,64 @@ impl fmt::Display for ParseError {
...
-        match self {
-            Receiver::P2pkh(_) => Typecode::P2pkh,
-            Receiver::P2sh(_) => Typecode::P2sh,
-            Receiver::Sapling(_) => Typecode::Sapling,
-            Receiver::Orchard(_) => Typecode::Orchard,
-            Receiver::Unknown { typecode, .. } => Typecode::Unknown(*typecode),
-        }
-    }
+            let mut padding = [0u8; PADDING_LEN];
+            padding[0..hrp.len()].copy_from_slice(&hrp.as_bytes());
```
Comment (therealyingtong) [inline components/zcash_address/src/kind/unified.rs:167]:
```suggestion
            padding[0..hrp.len()].copy_from_slice(hrp.as_bytes());
```

**Review by str4d — APPROVED** [review]
utACK a6e6f8ace2ca4679a1ad92bdee4bbcbd76c0227d after comments are addressed.

File: components/zcash_address/src/kind/unified.rs [hunk 8]
```diff
@@ -273,14 +239,10 @@ impl TryFrom<(&str, &[u8])> for Address {
...
-        result.try_into()
+        Self::try_from_receivers(result)
     }
-}
-
-impl TryFrom<Vec<Receiver>> for Address {
-    type Error = ParseError;
 
-    fn try_from(receivers: Vec<Receiver>) -> Result<Self, Self::Error> {
+    fn try_from_receivers(receivers: Vec<Self::Receiver>) -> Result<Self, ParseError> {
```
[the remark this answers is not in the document]
Comment (nuttycom) [reply components/zcash_address/src/kind/unified.rs:245]: This ends up not working:
```error[E0119]: conflicting implementations of trait `std::convert::TryFrom<std::vec::Vec<_>>`:
   --> components/zcash_address/src/kind/unified.rs:276:1
    |
276 | impl<T: Encoding> TryFrom<Vec<T::Item>> for T {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: conflicting implementation in crate `core`:
            - impl<T, U> TryFrom<U> for T
              where U: Into<T>;
```

**Review by nuttycom — APPROVED** [review]
ACK 82be04dfafecb15faa03a1d6e6699fcc53d800c6

File: components/zcash_address/src/kind/unified.rs [hunk 9]
```diff
@@ -132,52 +132,59 @@ pub(crate) mod private {
...
+                    <u32>::from(item.typecode()).try_into().unwrap(),
                 )
                 .unwrap();
                 CompactSize::write(&mut writer, addr.len()).unwrap();
                 writer.write_all(addr).unwrap();
             }
+        }
+
+        /// Returns the jumbled padded raw encoding of this Unified Address or viewing key.
+        fn to_bytes(&self, hrp: &str) -> Vec<u8> {
```
Comment (str4d) [inline components/zcash_address/src/kind/unified.rs:167]: This shouldn't be named `to_bytes`, because that is what a public method that output the raw bytes would use.
```suggestion
        /// Returns the jumbled padded raw encoding of this Unified Address or viewing key,
        /// as used in the string encoding.
        fn to_jumbled_bytes(&self, hrp: &str) -> Vec<u8> {
```
Alternatively, if this method is deleted by #465 (which could inline its contents into an encoding function) then I'd be fine with leaving this as-is in this PR.

File: components/zcash_address/src/kind/unified.rs [hunk 10]
```diff
@@ -261,27 +268,27 @@ pub trait FromReceivers: private::SealedContainer + std::marker::Sized {
             Err(ParseError::OnlyTransparent)
         } else {
             // All checks pass!
-            Ok(Self::from_inner(receivers))
+            Ok(Self::from_inner(items))
         }
     }
 }
 
 /// Trait providing common decoding logic for Unified containers.
```
Comment (str4d) [inline components/zcash_address/src/kind/unified.rs:276]: This comment is out of date, and my prior suggestion stands:
```suggestion
/// Trait for for Unified containers, that exposes the items within them.
```

**Review by str4d — APPROVED** [review]
utACK 82be04dfafecb15faa03a1d6e6699fcc53d800c6 modulo comments being addressed (either here or in #465).

File: components/zcash_address/src/kind/unified.rs (hunk 9 above)
Comment (nuttycom) [reply components/zcash_address/src/kind/unified.rs:167]: This will be fixed in #465

**Review by therealyingtong — COMMENTED** [review]
utACK 566c973ea7994fa2ae13c8e8d5e2d9ba2e93bfbf.

File: components/zcash_address/src/kind/unified.rs [hunk 11]
```diff
@@ -112,108 +96,97 @@ impl Typecode {
...
+        fn write_raw_encoding<W: Write>(&self, mut writer: W) {
+            for item in &self.items() {
+                let addr = item.data();
+                CompactSize::write(
+                    &mut writer,
+                    <u32>::from(item.typecode()).try_into().unwrap(),
+                )
+                .unwrap();
+                CompactSize::write(&mut writer, addr.len()).unwrap();
+                writer.write_all(addr).unwrap();
```
Comment (daira) [inline components/zcash_address/src/kind/unified.rs:162]:
```suggestion
                let data = item.data();
                CompactSize::write(
                    &mut writer,
                    <u32>::from(item.typecode()).try_into().unwrap(),
                )
                .unwrap();
                CompactSize::write(&mut writer, data.len()).unwrap();
                writer.write_all(data).unwrap();
```

File: components/zcash_address/src/kind/unified.rs [hunk 12]
```diff
@@ -241,7 +214,7 @@ impl TryFrom<(&str, &[u8])> for Address {
                     length
```
Comment (daira) [inline components/zcash_address/src/kind/unified.rs:214]: "address" -> "item" on the preceding line.

File: components/zcash_address/src/kind/unified.rs [hunk 13]
```diff
@@ -299,251 +268,27 @@ impl TryFrom<Vec<Receiver>> for Address {
...
-            writer.write_all(addr).unwrap();
-        }
-
-        let mut padding = [0u8; PADDING_LEN];
-        padding[0..hrp.len()].copy_from_slice(&hrp.as_bytes());
-        writer.write_all(&padding).unwrap();
-
-        f4jumble::f4jumble(&writer.into_inner()).unwrap()
-    }
+/// Trait for for Unified containers, that exposes the items within them.
```
Comment (daira) [inline components/zcash_address/src/kind/unified.rs:276]:
```suggestion
/// Trait for Unified containers, that exposes the items within them.
```

File: components/zcash_address/src/kind/unified/address.rs [hunk 14]
```diff
@@ -0,0 +1,310 @@
...
+            let decoded = Address::try_from_bytes(hrp.as_str(), &bytes[..]);
+            prop_assert_eq!(decoded, Ok(ua));
+        }
+    }
+
+    #[test]
+    fn padding() {
+        // The test cases below use `Address(vec![Receiver::Orchard([1; 43])])` as base.
+
+        // Invalid padding ([0xff; 16] instead of [b'u', 0x00, 0x00, 0x00...])
```
Comment (daira) [inline components/zcash_address/src/kind/unified/address.rs:175]:
```suggestion
        // Invalid padding ([0xff; 16] instead of [0x75, 0x00, 0x00, 0x00...])
```

**Review by daira — COMMENTED** [review]
Post-hoc utACK.

File: components/zcash_address/src/kind/unified/address.rs (hunk 14 above)
Comment (nuttycom) [reply components/zcash_address/src/kind/unified/address.rs:175]: Addressed in #465

File: components/zcash_address/src/kind/unified.rs (hunk 13 above)
Comment (nuttycom) [reply components/zcash_address/src/kind/unified.rs:276]: Resolved in #465

File: components/zcash_address/src/kind/unified.rs (hunk 12 above)
Comment (nuttycom) [reply components/zcash_address/src/kind/unified.rs:214]: Resolved in #465

File: components/zcash_address/src/kind/unified.rs (hunk 11 above)
Comment (nuttycom) [reply components/zcash_address/src/kind/unified.rs:162]: Resolved in #465

**Comment by nuttycom** [comment]
Ugh. These changes apparently alter encoding and decoding in some fashion that is not backwards-compatible; zcashd tests now fail as follows:
```
gtest/test_keys.cpp:159: Failure
Expected equality of these values:
  encoded
    Which is: "u16ut73k64juzu6ju0was6qu7gd7qz03rawshwntm00x970k2ct5mwj56rdxsxc88qpn5kvqn53zchlntxk84xkkhn4fjt3dfynl5vymdfeh0m9xe0w80fvmjmpx4mefjtwj8xgngphwp"
  expected
    Which is: "u1t7y3ndv46tvcde7x4685ajmgk59pd092lhs4wanwldh4fm7ucjr0t44hfz5jcufzuakefzuqvz7j0aytsnfw4peydx8u8tjsq4w8uks6rysc655mxkj6wxxhpgknys53eyxpk89xysc"
gtest/test_keys.cpp:159: Failure
Expected equality of these values:
  encoded
    Which is: "u1ets5s0lr9yve6j9qd2ausvpp2c7wfu9uwuknnj2gveqach5p987vq775rslv2gygmh2gwzkxhfeq54n42pesdr6fn5nfhw5l9gytu2jl50q9ph4m0v9gsgrw02m62skjjqf2aetpyz0anjf8lhvnekh5wxm4wfulkac2fdajufuzm8ka4gcf44p7ndan7cez4s0pkmp8utz6jz67l5f"
  expected
    Which is: "u1fehkejdm60a8q55gsevqlxgf29j8gl7sd946unjs4nl44sc440rtet5ugq72dcx9pjth9l23rpjufuzcwh75yqezu25au289pqrtalq67wn40fxqw0ln7zxwz9ysxuu0z93wrgnmfq7k3fn6tzc0v7rz9g3pjgwuqtlkzxhsx89az9ehh3l5j5quuurwn7n3tjxlan25rnq4gjza8t6"
gtest/test_keys.cpp:159: Failure
Expected equality of these values:
  encoded
    Which is: "u1nk570aamy4zmhelz6ka03fzy4s7f9r4kevfmgce3y56qnjqzmht6hy7r38tkwdtg9a4ccxe3dxt4ktj4ajn9ky4ls6jejc9rgfdunsuguhxdmpj05ur6ducdwlhjm92jxljry7tg2dk"
  expected
    Which is: "u1djhgxw5ytztc5mu22r4ms5gym8dwhg8422fguxyvltexv8xurgs8cr0ukrdys7fvhqmmasafgfe0gt5wn0mujnc34gtmcw49uedkhpzyxz49zvx5c9uq0hjd5n7trgsnejhjqmsvr6c"
gtest/test_keys.cpp:159: Failure
Expected equality of these values:
  encoded
    Which is: "u1rqyru8lqqhyzdljsersz7hnhxty5y6ycctl2dua8jeqjryapcfvvhpktnpcagasktacjnmtt9p0q6tkulzg002rxvarsf8ecc7zsljz5d09xtqnm536qsme27hpzg7luqc85nkd6ahts4lkm0zduqnqlqrcycmtcl4sk3l54hqt7l3hfdufcgekmpawssfnzlzjcfwm0cehxkde0cv9"
  expected
    Which is: "u15e2n256tkch79fwyzvlf3sxflfrwrfm6d3me90nv92fkeuwne4wsyuezenq5jshqng09nwly0575qsp76hhxxwkjcsskcefl85l0tey38w26tlleuxzfgm8p72rt5703cr8xuy0uw7lrctngg9k7zu8zufuv9qxc6tyjrx3x3gjvykdmyam4yv3y4q7jflx0p0m94pfsw9hzk7a28py"
gtest/test_keys.cpp:159: Failure
Expected equality of these values:
  encoded
    Which is: "u1jm8mec2lsre3ffeepmtts47k833m3rqe0rhmzj97xrg77a6fljza36fjhw4dccvm9l2na7lpafujfa5katw89yw66hs0ca5tt6fepsjv6p0uu9swdavrc8pxml40fw8evkv20vja8nwxn76na0m7ngt2l0ys62570waujqst5q7yt5tn"
  expected
    Which is: "u1kalkm2vqrgqm8llqeuh53rwzlet5gea4mkdw97j9pa3rcetvzv3lkk3e0u3543vptgt2k0uaf88608fu3ucefvwewyz9tqweaj3wull0pd70mtnhywek0l5vazca6ewf4rdmwxq8f2s4pm5hqu6meg9zgtgzv98rxzh2wx5vevys04es"
gtest/test_keys.cpp:159: Failure
Expected equality of these values:
  encoded
    Which is: "u1prhztjq7ylfew7zlsa4squ4dc9yuh6ytmlale3yysw8gmjlddalnezx4fpdqsxgycf9ywtna5ewhd3jcdmskhs4qv5zaexltw6u80lneef85kumr9f6h3vf6fazudkgayv4w3njtvh34ad3fxex0alcwfwpd5kt5cw0kx8yjstxxp7v7rgcj8kg7uuyr7u76eh5y0jqw42s8yunuhgr"
  expected
    Which is: "u1m0vzn78gh0ymq5kqz4lpd4095wpue8hnhzss5z4sl38szn8vw6h94xuvcjv5ahknpmlra67uecvnkms9yfqx4s7hsnszzmcpgvxr20lh459ps3u3wf6mrzwe6x9kdj8tp0a6csed2emxp6q7qnwatd2xm4psjh4r4g9phff54tsuxe5768thsxssavxrfytpdpm72kjsrypayzwgq9x"
```
