### PR TITLE
zcash_client_sqlite: Initialize the scan queue as part of `init_blocks_table`

### LINKED ISSUE #898: Send fails: Tree does not contain a root at address
In the Android SDK, which is operating upon the new SbS sync and the sync is in progress, we can reproduce `RuntimeException: Error while creating transaction: An error occurred in querying or updating a note commitment tree: Tree does not contain a root at address Address { level: Level(0), index: 127765 }`, which comes from the Rust layer of the SDK.

Full log:
```
TransactionEncoderImpl.createSpend(): creating transaction to spend Zatoshi(value=50) zatoshi to ****rgd9 with memo: test send
SaplingParamTool.validate$zcash_android_sdk_1_20_0_beta01_release(): Param files  both exist!
TransactionEncoderImpl.createSpend(): params exist! attempting to send...
TransactionEncoderImpl.createSpend(): Caught exception while creating transaction.
java.lang.RuntimeException: Error while creating transaction: An error occurred in querying or updating a note commitment tree: Tree does not contain a root at address Address { level: Level(0), index: 127765 }
	at cash.z.ecc.android.sdk.internal.jni.RustBackend.createToAddress(Native Method)
	at cash.z.ecc.android.sdk.internal.jni.RustBackend.access$createToAddress(RustBackend.kt:19)
	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.createToAddress(Unknown Source:0)
	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.access$createToAddress(RustBackend.kt:369)
	at cash.z.ecc.android.sdk.internal.jni.RustBackend$createToAddress$2.invokeSuspend(RustBackend.kt:303)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
```

Here are a few more hints:
- reproducible on the Testnet
- with SbS sync in progress
- old/new wallet makes no difference

### LINKED ISSUE #902: Insert a "Scanned" range prior to the wallet birthday
A beta tester of the iOS wallet reported that a brand new wallet appeared to attempt to scan from Sapling activation. This is likely because a "Scanned" range isn't being inserted for `SaplingActivation..=WalletBirthday`. We should insert this.

### PR DESCRIPTION
**Pull request by nuttycom**
This is a partial solution to #902 and #898. The complete fix, which avoids the need to fully scan the subtree containing the wallet's birthday height, will be achievable once #901 is complete. 

Fixes #902
Fixes #898

### CODE REVIEW

File: zcash_client_sqlite/src/wallet/init.rs [hunk 1]
```diff
@@ -309,15 +315,27 @@ pub fn init_blocks_table<P: consensus::Parameters>(
...
+            wdb.conn.0.execute(
+                "INSERT INTO scan_queue (block_range_start, block_range_end, priority)
+                 VALUES (:block_range_start, :block_range_end, :priority)",
+                named_params![
+                   ":block_range_start": u32::from(std::cmp::min(sapling_activation, height)),
+                   ":block_range_end": u32::from(height + 1),
+                   ":priority": priority_code(&ScanPriority::Ignored)
+                ],
+            )?;
+        }
```
Comment (daira) [inline zcash_client_sqlite/src/wallet/init.rs:337]: What about existing databases? Doesn't this need to be a migration?

File: zcash_client_sqlite/src/wallet/init.rs [hunk 2]
```diff
@@ -309,15 +315,27 @@ pub fn init_blocks_table<P: consensus::Parameters>(
...
+            named_params![
+                ":height": u32::from(height),
+                ":hash": hash.0,
+                ":time": time,
+                ":sapling_tree": sapling_tree,
             ],
         )?;
 
+        if let Some(sapling_activation) = wdb.params.activation_height(NetworkUpgrade::Sapling) {
+            wdb.conn.0.execute(
```
Comment (daira) [inline zcash_client_sqlite/src/wallet/init.rs:328]: Consider adding a `debug!` here.

File: zcash_client_sqlite/src/wallet/init.rs [hunk 3]
```diff
@@ -309,15 +315,27 @@ pub fn init_blocks_table<P: consensus::Parameters>(
...
+                "INSERT INTO scan_queue (block_range_start, block_range_end, priority)
+                 VALUES (:block_range_start, :block_range_end, :priority)",
+                named_params![
+                   ":block_range_start": u32::from(std::cmp::min(sapling_activation, height)),
```
Comment (daira) [inline zcash_client_sqlite/src/wallet/init.rs:332]:
```suggestion
                   ":block_range_start": u32::from(start_height),
```
(if the above suggestion is taken).

File: zcash_client_backend/src/data_api/scanning.rs [hunk 4]
```diff
@@ -6,7 +6,9 @@ use zcash_primitives::consensus::BlockHeight;
 /// Scanning range priority levels.
 #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
 pub enum ScanPriority {
-    /// Block ranges that have already been scanned have lowest priority.
+    /// Block ranges that are ignored have lowest priority.
+    Ignored,
```
Comment (daira) [inline zcash_client_backend/src/data_api/scanning.rs:10]: There are a bunch of places where we use the Sapling activation height as the first block height that should potentially be scanned. If I understand correctly, this PR is marking the priority of the blocks between the Sapling activation height and the wallet's birthday as ignored, with the intent that they stay permanently ignored.

Wouldn't it be simpler to explicitly store the birthday and use that in place of the Sapling activation height? That would be a simpler data model with fewer states.

(I know that it is possible to have a rollback just after the wallet is initialised that effectively rolls back its birthday. If that ends up being too complex to handle in the approach I'm suggesting then I can see the rationale for doing it this way.)

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 5]
```diff
@@ -1212,4 +1220,102 @@ mod tests {
             ]
         );
     }
+
+    #[test]
+    fn init_blocks_table_creates_scanned_range() {
```
Comment (daira) [inline zcash_client_sqlite/src/wallet/scanning.rs:1225]:
```suggestion
    fn init_blocks_table_creates_ignored_range() {
```

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 6]
```diff
@@ -1212,4 +1220,102 @@ mod tests {
...
+            &mut db_data,
+            birthday_height,
+            BlockHash([1; 32]),
+            1,
+            &[0x0, 0x0, 0x0],
+        )
+        .unwrap();
+
+        let expected = vec![
+            // The range below the wallet's birthday height is ignored
```
Comment (daira) [inline zcash_client_sqlite/src/wallet/scanning.rs:1252]: This is not the range below the wallet's birthday height; it is the range up to and including the birthday height. Is that the intent?

File: zcash_client_sqlite/src/wallet/scanning.rs [hunk 7]
```diff
@@ -1212,4 +1220,102 @@ mod tests {
...
+            scan_range(
+                u32::from(sap_active)..u32::from(birthday_height - 1000),
+                Ignored,
+            ),
+        ];
+
+        assert_matches!(
+            suggest_scan_ranges(&db_data.conn, Ignored),
+            Ok(scan_ranges) if scan_ranges == expected        );
```
Comment (daira) [inline zcash_client_sqlite/src/wallet/scanning.rs:1319]: Extraneous whitespace.

**Review by daira — DISMISSED** [review]
utACK with comments.

File: zcash_client_backend/src/data_api/scanning.rs (hunk 4 above)
Comment (daira) [reply zcash_client_backend/src/data_api/scanning.rs:10]: I see the #901 is about doing precisely that. But the issue is that if you do this change first and #901 later, then you've already complicated the data model by adding the "ignored" priority, and can't undo that.

File: zcash_client_sqlite/src/wallet/scanning.rs (hunk 6 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/wallet/scanning.rs:1252]: Yes; the birthday height is the height of the current chain tip at the time that the wallet is created; by definition, the wallet can receive no transactions within that block.

File: zcash_client_backend/src/data_api/scanning.rs (hunk 4 above)
Comment (nuttycom) [reply zcash_client_backend/src/data_api/scanning.rs:10]: I think that the notion of having an ignored range could actually be generally useful; one hypothetical use case is that someone who knows that their wallet has been offline for a long period of time (say, for example, a paper/cold wallet for which they never gave out any addresses) could explicitly inform the wallet that it should ignore the range since the last height that they interacted with it, and thereby avoid scanning costs. So even after #901 I think it's good to keep the `Ignored` case; I just hadn't really thought about it before or I might have included the behavior I'm implementing here in the first draft.

**Comment by nuttycom** [comment]
[force-pushed](https://github.com/zcash/librustzcash/compare/8dc851f3d488a7a8ea93c2a63bb3c976945a87db..b3be0318c69d129599f7bf94845251cc5d58f9a3) to address comments from review.

File: zcash_client_sqlite/src/wallet/scanning.rs (hunk 6 above)
Comment (daira) [reply zcash_client_sqlite/src/wallet/scanning.rs:1252]:
```suggestion
            // The range up to and including the wallet's birthday height is ignored.
```

**Review by daira — DISMISSED** [review]
utACK with minor non-blocking suggestion.

**Review by daira — APPROVED** [review]
utACK
