### PR TITLE
fix: zcash_client_sqlite take coinbase maturity into account

### LINKED ISSUE #821: Verify whether shielding functionality takes into account coinbase maturity.
If a miner mines directly to the transparent address of an autoshielding mobile wallet, we need to ensure that the coins in question have satisfied the coinbase maturity constraint before we attempt to shield them.

### PR DESCRIPTION
**Pull request by schell**
These changes add a query to exclude immature coinbase outputs from note selection.
 
Fixes #821.

Requirement for:
* https://github.com/zcash/wallet/issues/89

### CODE REVIEW

File: zcash_client_sqlite/src/wallet/transparent.rs [hunk 1]
```diff
@@ -1045,6 +1045,27 @@ pub(crate) fn excluding_wallet_internal_ephemeral_outputs(
...
+///   used as a strictly constricting clause on the set of outputs.
+pub(crate) fn excluding_immature_coinbase_outputs(tx: &str) -> String {
+    format!(
+        r#"
+        -- the output is _not_ a coinbase output
+        {tx}.tx_index != 0
+        -- or tx is mined and has at least 100 confirmations
+        OR (
+            {tx}.mined_height < :target_height -- tx is mined
+            AND :target_height - {tx}.mined_height >= 100
```
Comment (nuttycom) [inline zcash_client_sqlite/src/wallet/transparent.rs]: Since we're already in a `format!` block, maybe introduce a constant?
```suggestion
            AND :target_height - {tx}.mined_height >= {COINBASE_MATURITY_BLOCKS}
```

File: zcash_client_sqlite/src/wallet/transparent.rs [hunk 2]
```diff
@@ -1045,6 +1045,27 @@ pub(crate) fn excluding_wallet_internal_ephemeral_outputs(
...
+///   outputs that have already otherwise been verified to be spendable, i.e. it must be
+///   used as a strictly constricting clause on the set of outputs.
+pub(crate) fn excluding_immature_coinbase_outputs(tx: &str) -> String {
+    format!(
+        r#"
+        -- the output is _not_ a coinbase output
+        {tx}.tx_index != 0
+        -- or tx is mined and has at least 100 confirmations
+        OR (
+            {tx}.mined_height < :target_height -- tx is mined
```
Comment (nuttycom) [inline zcash_client_sqlite/src/wallet/transparent.rs]: This condition seems like it shouldn't be necessary, because the `:target_height - {tx}.mined_height` on the next line will always return `NULL` and thus the test against `{COINBASE_MATURITY_BLOCKS}` will fail.
```suggestion
```

File: zcash_client_sqlite/src/wallet/transparent.rs [hunk 3]
```diff
@@ -1045,6 +1045,27 @@ pub(crate) fn excluding_wallet_internal_ephemeral_outputs(
...
+            AND :target_height - {tx}.mined_height >= 100
+        )
```
Comment (nuttycom) [inline zcash_client_sqlite/src/wallet/transparent.rs]:
```suggestion
        OR :target_height - {tx}.mined_height >= {COINBASE_MATURITY_BLOCKS}
```

File: zcash_client_backend/src/data_api/testing/pool.rs [hunk 4]
```diff
@@ -4939,3 +4939,81 @@ pub fn receive_two_notes_with_same_value<T: ShieldedPoolTester>(
...
+        AddressType::DefaultExternal,
+        value,
+    )];
+    let total_value = value;
+
+    // `st.generate_next_block` with multiple outputs.
+    let pre_activation_block = CachedBlock::none(st.sapling_activation_height() - 1);
+    let prior_cached_block = st.latest_cached_block().unwrap_or(&pre_activation_block);
+    let h = prior_cached_block.height() + 1;
+    st.generate_block_at(
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/testing/pool.rs]: This won't correctly add a transparent coinbase output, because we don't (yet) support transparent inputs and outputs in compact blocks. One possible solution is to update to `lightwallet-protocol v0.4.0` and then update the test harness accordingly, but that really depends on `scan_cached_blocks` correctly handling coinbase outputs, which I'm currently working on. Alternately, we need to get https://github.com/zcash/librustzcash/pull/1893 merged so that we can explicitly create a coinbase transaction and add it to a block using `fake_compact_block_from_tx`.

File: zcash_client_backend/src/data_api/testing/pool.rs [hunk 5]
```diff
@@ -4954,3 +4957,114 @@ pub fn receive_two_notes_with_same_value<T: ShieldedPoolTester>(
...
 }
+
+fn build_coinbase_tx(
+    network: &LocalNetwork,
+    value: Zatoshis,
+    recipient: TransparentAddress,
+    miner_data: Option<PushValue>,
+) -> zcash_primitives::transaction::builder::BuildResult {
+    let build_config = BuildConfig::Coinbase { miner_data };
+    let mut builder = Builder::new(network.clone(), BlockHeight::from_u32(1), build_config);
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/testing/pool.rs]: For fidelity, this shouldn't hardcode the target height, but should take it as an argument.

File: zcash_client_backend/src/data_api/testing/pool.rs [hunk 6]
```diff
@@ -4954,3 +4957,114 @@ pub fn receive_two_notes_with_same_value<T: ShieldedPoolTester>(
...
+) {
+    let mut st = TestDsl::with_sapling_birthday_account(dsf, cache).build::<T>();
+
+    // Get the default transparent address
+    let (t_addr, _) = st.get_account().usk().default_transparent_address();
+
+    let coinbase_value = Zatoshis::const_from_u64(50000);
+
+    // Construct the coinbase transaction and mine the block
+    let coinbase_build_result = build_coinbase_tx(st.network(), coinbase_value, t_addr, None);
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/testing/pool.rs]: Given that the Sapling birthday height is far above block height 1, this transaction should actually be expired when `generate_next_block_from_tx` is called, but as we don't have that consensus check in place it's incorrectly succeeding. We should probably do that check in `generate_next_block_from_tx` because there are cases around transaction expiry that we should be testing in some places.

File: zcash_client_backend/src/data_api/testing/pool.rs [hunk 7]
```diff
@@ -4954,3 +4957,114 @@ pub fn receive_two_notes_with_same_value<T: ShieldedPoolTester>(
...
+    let coinbase_tx = coinbase_build_result.transaction();
+    let (h, _) = st.generate_next_block_from_tx(0, coinbase_tx);
+    st.scan_cached_blocks(h, 1);
+
+    // Store the UTXO in the wallet (not sure about this step)
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/testing/pool.rs]: This is okay; another way to do this would be to call `decrypt_and_store_transaction`.

File: zcash_client_backend/src/data_api/testing/pool.rs [hunk 8]
```diff
@@ -4954,3 +4957,114 @@ pub fn receive_two_notes_with_same_value<T: ShieldedPoolTester>(
...
+        .unwrap();
+    assert!(
+        !spendable_utxos.is_empty(),
+        "Coinbase output should be spendable at blockheight {latest_height} \
+        with {confirmations} confirmations since the coinbase tx was mined (at {h})\n \
+        target_height {target_height:?} - coinbase_tx.mined_height {h} = {}",
+        u32::from(target_height) - u32::from(h)
+    );
+
+    // TODO(schell): Verify we can propose shielding the coinbase utxo
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/testing/pool.rs]: This is probably where transaction expiry will bite you.

File: zcash_client_sqlite/src/wallet/transparent.rs [hunk 9]
```diff
@@ -1045,6 +1045,34 @@ pub(crate) fn excluding_wallet_internal_ephemeral_outputs(
...
+/// - The parent is responsible for enclosing this condition in parentheses as appropriate.
+/// - The parent is responsible for ensuring that this condition will only be checked for
+///   outputs that have already otherwise been verified to be spendable, i.e. it must be
+///   used as a strictly constricting clause on the set of outputs.
+pub(crate) fn excluding_immature_coinbase_outputs(tx: &str) -> String {
+    // FIXME: If a coinbase transaction is discovered via the get_compact_utxos RPC call
+    // we won't have sufficient info to identify it as coinbase, so it may not be excluded
+    // unless decrypt_and_store_transaction has been called on the transaction that produced it.
+    //
+    // To fix this we'll need to add the `tx_index` field to the GetAddressUtxosReply proto type.
```
Comment (nullcopy) [inline zcash_client_sqlite/src/wallet/transparent.rs:1063]: Is there an issue tracking this?

File: zcash_client_sqlite/src/wallet/transparent.rs [hunk 10]
```diff
@@ -1045,6 +1045,34 @@ pub(crate) fn excluding_wallet_internal_ephemeral_outputs(
...
+    format!(
+        r#"
+        NOT (
+            -- the output is a coinbase output
+            -- -- TODO(schell): After https://github.com/zcash/librustzcash/pull/2036 merges we may be able
```
Comment (nullcopy) [inline zcash_client_sqlite/src/wallet/transparent.rs]: So is this PR blocked on #2036 ?

File: zcash_client_memory/src/input_source.rs [hunk 11]
```diff
@@ -155,6 +155,8 @@ impl<P: consensus::Parameters> InputSource for MemoryWalletDb<P> {
         target_height: TargetHeight,
         confirmations_policy: ConfirmationsPolicy,
     ) -> Result<Vec<WalletUtxo>, Self::Error> {
+        // TODO: take into consideration coinbase maturity
+        // See <https://github.com/zcash/librustzcash/issues/821>
```
Comment (nullcopy) [inline zcash_client_memory/src/input_source.rs:159]: Did you mean to leave this TODO here? This PR resoves #821, right?

File: zcash_client_sqlite/src/wallet/transparent.rs (hunk 9 above)
Comment (schell) [reply zcash_client_sqlite/src/wallet/transparent.rs:1063]: Good call. I've created one at https://github.com/zcash/lightwallet-protocol/issues/17.

File: zcash_client_sqlite/src/wallet/transparent.rs (hunk 10 above)
Comment (schell) [reply zcash_client_sqlite/src/wallet/transparent.rs]: It's not blocked, as the `IFNULL(...)` implementation works around this, but feels a bit hacky.

File: zcash_client_memory/src/input_source.rs (hunk 11 above)
Comment (schell) [reply zcash_client_memory/src/input_source.rs:159]: This is left for folks implementing `zcash_client_memory`, just as a reminder.

File: zcash_client_backend/src/data_api/testing/pool.rs [hunk 12]
```diff
@@ -4954,3 +4957,113 @@ pub fn receive_two_notes_with_same_value<T: ShieldedPoolTester>(
         assert_eq!(T::note_value(note.note()), value);
     }
 }
+
+#[cfg(feature = "pczt")]
+fn build_coinbase_tx(
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/testing/pool.rs]: Naming nit: this is specifically for transparent coinbase.
```suggestion
fn build_transparent_coinbase_tx(
```

File: zcash_client_backend/src/data_api/testing/pool.rs [hunk 13]
```diff
@@ -4954,3 +4957,113 @@ pub fn receive_two_notes_with_same_value<T: ShieldedPoolTester>(
...
+    network: &LocalNetwork,
+    target_height: BlockHeight,
```
Comment (nuttycom) [inline zcash_client_backend/src/data_api/testing/pool.rs]: nonblocking nit:
```suggestion
    target_height: TargetHeight,
```

File: zcash_client_sqlite/src/wallet/transparent.rs (hunk 10 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/wallet/transparent.rs]: #2036 actually doesn't change the situation here, I don't believe; you're thinking of a yet-to-be-opened PR that actually implements transparent output detection as part of normal block scanning. Even with that, though, wallets will have the option to use the direct UTXO retrieval strategy, so I think this will have to remain `IFNULL` and this TODO can be removed.

**Review by nuttycom — DISMISSED** [review]
utACK ddddf660e897d42333561ddefe7827fde81ea6fa

File: zcash_client_sqlite/src/wallet/transparent.rs [hunk 14]
```diff
@@ -1067,9 +1067,6 @@ pub(crate) fn excluding_immature_coinbase_outputs(tx: &str) -> String {
         r#"
         NOT (
             -- the output is a coinbase output
-            -- -- TODO(schell): After https://github.com/zcash/librustzcash/pull/2036 merges we may be able
-            -- -- to simplify this query to:
-            -- -- {tx}.tx_index == 0
             IFNULL({tx}.tx_index, 1) == 0
```
Comment (nuttycom) [inline zcash_client_sqlite/src/wallet/transparent.rs:1070]: Oh, actually, `{tx}.tx_index == 0` will always return `false` if `{tx}.tx_index IS NULL` anyway, so this `IFNULL` is superfluous.

Comment (nuttycom) [reply zcash_client_sqlite/src/wallet/transparent.rs:1070]: Any comparison `NULL == foo` returns `false`.

Comment (schell) [reply zcash_client_sqlite/src/wallet/transparent.rs:1070]: Previously, when using `{tx}.tx_index == 0`, tests would fail because many of the test transactions were erroneously being filtered by this condition. For example, if `tx_index` is set to `NULL`, `{tx}.tx_index == 0` evaluates to `NULL`, **not false**. I checked this by removing the filter and adding `(t.tx_index == 0) AS tx_index_eq_zero` to `get_spendable_transparent_outputs`, but you can also verify in sqlite itself:

```sql
sqlite> SELECT (NULL == 0) WHERE 1;

sqlite> SELECT (0 == 0) WHERE 1;
1
sqlite> SELECT (1 == 0) WHERE 1;
0
```

The failing tests were:

```
failures:
    wallet::orchard::tests::shield_transparent
    wallet::sapling::tests::shield_transparent
    wallet::transparent::tests::put_received_transparent_utxo
    wallet::transparent::tests::transparent_balance_across_shielding
    wallet::transparent::tests::transparent_balance_spendability
```

Using `IFNULL` here was the crux of getting the new coinbase maturity test to pass, while also keeping the previous tests passing, since they don't insert a `tx_index`. 

*edit*
Otherwise what happens is the whole `excluding_immature_coinbase_outputs` essentially simplifies down to `NOT NULL` preventing the transaction from being selected, even though it is _not_ a coinbase transaction...
