### PR TITLE
zcash_client_sqlite: Fix balance in expired unmined transaction history.

### LINKED ISSUE #1292: zcash_client_sqlite: Value of expired transactions is reported incorrectly from the `v_transactions` view.
At present, the `sapling_received_notes` and `orchard_received_notes` tables both have a `spent` column, which references the transaction in which the note is spent, if any. This works fine under ordinary circumstances, but if a transaction expires without being mined, the reference to the transaction is removed from the `spent` column. This then causes a problem for the `v_transactions` view, which can no longer correctly represent the original balance of the transaction.

The fix for this is to use a junction table between the `*received_notes` tables and the spending transactions, and for queries that use this association to determine spentness to verify whether or not a transaction has expired instead of simply checking whether or not the `spent` column is null.

### LINKED ISSUE #1299: zcash_client_sqlite: Do not delete received notes in chain rollback.
We should not discard "failed received notes" - they may have memo data associated with them that we can still read, and we just need to be sure that they do not contribute to balance or spendability.

### PR DESCRIPTION
**Pull request by nuttycom**
Fixes #1292
Fixes #1299

### CODE REVIEW

File: zcash_client_sqlite/src/wallet.rs [hunk 1]
```diff
@@ -1913,36 +1956,15 @@ pub(crate) fn truncate_to_height<P: consensus::Parameters>(
...
-            );",
-            [u32::from(block_height)],
-        )?;
-
         // Do not delete sent notes; this can contain data that is not recoverable
         // from the chain. Wallets must continue to operate correctly in the
         // presence of stale sent notes that link to unmined transactions.
+        // Also, do not delete received notes; they may contain memo data that is
+        // not recoverable; balance APIs must ensure that un-mined received notes
+        // do not count towards spendability or transaction balalnce.
```
Comment (daira) [inline zcash_client_sqlite/src/wallet.rs:1964]:
```suggestion
        // do not count towards spendability or transaction balance.
```
Non-blocking.

File: zcash_client_sqlite/src/wallet.rs [hunk 2]
```diff
@@ -1245,10 +1253,17 @@ pub(crate) fn get_wallet_summary<P: consensus::Parameters>(
...
+             -- and the received txo is unspent
+             AND u.id NOT IN (
+               SELECT transparent_received_output_id
+               FROM transparent_received_output_spends txo_spends
+               JOIN transactions tx
+                 ON tx.id_tx = txo_spends.transaction_id
+               WHERE tx.block IS NOT NULL -- the spending tx is mined
+               OR tx.expiry_height IS NULL -- the spending tx will not expire
+               OR tx.expiry_height > :stable_height -- the spending tx is unexpired
+             )
```
Comment (daira) [inline zcash_client_sqlite/src/wallet.rs:1266]: Can some of the duplication in the SQL be avoided by defining a view (or views for Sapling and Orchard) of notes that are considered spent? Non-blocking.

Comment (daira) [reply zcash_client_sqlite/src/wallet.rs:1266]: Oh, the PR does create such views. I don't understand why there is so much SQL duplication, then. It looks pretty error-prone to maintain :-/

**Review by daira — APPROVED** [review]
utACK with comments.

File: zcash_client_sqlite/src/wallet.rs (hunk 2 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/wallet.rs:1266]: I want to make a pass after 1.0 is out to do the refactoring to eliminate a whole bunch of the duplication, but I want that to be a pure refactoring rather than part of fixing bugs.

File: zcash_client_sqlite/src/wallet/init.rs [hunk 3]
```diff
@@ -584,26 +611,19 @@ mod tests {
             r#"CREATE INDEX orchard_received_notes_account ON orchard_received_notes (
                 account_id ASC
             )"#,
-            r#"CREATE INDEX orchard_received_notes_spent ON orchard_received_notes (
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet/init.rs:587]: Should these index removals be replaced with index creations for the foreign keys of the new junction tables?

File: zcash_client_sqlite/src/wallet.rs [hunk 4]
```diff
@@ -1898,7 +1923,25 @@ pub(crate) fn truncate_to_height<P: consensus::Parameters>(
...
+        "DELETE FROM scan_queue
+        WHERE block_range_start >= :new_end_height",
+        named_params![":new_end_height": u32::from(block_height + 1)],
+    )?;
+    conn.execute(
+        "UPDATE scan_queue
+        SET block_range_end = :new_end_height
+        WHERE block_range_end > :new_end_height",
+        named_params![":new_end_height": u32::from(block_height + 1)],
+    )?;
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet.rs:1940]: Why was this moved to earlier in the truncation process?

**Review by str4d — APPROVED** [review]
Concept ACK fada46e6383ccdb78eff56f7709c9246426a80db. I reviewed `zcash_client_sqlite/src/wallet/init.rs` for the effects of the migration changes on the tables, and skimmed the rest of the PR. I did not review any changes to SQL queries.

File: zcash_client_sqlite/src/wallet.rs (hunk 4 above)
Comment (nuttycom) [reply zcash_client_sqlite/src/wallet.rs:1940]: It was previously guarded by the 'if' statement below, meaning that the scan queue was not being correctly updated in all cases. This was one of the bugs fixed by this PR.

File: zcash_client_sqlite/src/wallet.rs [hunk 5]
```diff
@@ -2037,11 +2033,15 @@ pub(crate) fn get_unspent_transparent_output(
     let mut stmt_select_utxo = conn.prepare_cached(
         "SELECT u.prevout_txid, u.prevout_idx, u.script, u.value_zat, u.height
          FROM utxos u
-         LEFT OUTER JOIN transactions tx
-         ON tx.id_tx = u.spent_in_tx
          WHERE u.prevout_txid = :txid
          AND u.prevout_idx = :output_index
-         AND tx.block IS NULL",
+         AND u.id NOT IN (
+            SELECT txo_spends.id
```
Comment (str4d) [inline zcash_client_sqlite/src/wallet.rs:2039]: Bug: this should be:
```suggestion
            SELECT txo_spends.transparent_received_output_id
```

Bug found by Lukas while testing the Zashi shield funds button.
